fluent/fluent-operator

- cmd/fluentbit-operator/configuration.go
- cmd/fluentbit-operator/fluentbit/fluentbit.go
- deploy/helm/fluentbit-operator/templates/configmap.yaml
- deploy/helm/fluentbit-operator/values.yaml
Signed-off-by: huanggze <“loganhuang@yunify.com”>
> now able to change configmap-reload image

- cmd/fluentbit-operator/fluentbit/fluentbit.go
> fix: log mount path

- cmd/fluentbit-operator/configuration.go
- cmd/fluentbit-operator/fluentbit/fluentbit.go
> feat: update fluent bit once operator config changed

- manifests/logging-stack/fluentbit-fluentBit.yaml
> manifests: add tolerations to fluent bit

- cmd/migrator/main.go
1. Read old config from the configmap `fluent-bit-output-config` in `kubesphere-logging-system`
2. decode config data
3. migrating and updating
**Note: the migrator is applicable for kubesphere 2.x users only**
----
Example: config data in the ConfigMap
```json
[
{
"type":"fluentbit_output",
"name":"fluentbit-output-es",
"parameters":[
{
"name":"Logstash_Format",
"value":"On"
},
{
"name":"Replace_Dots",
"value":"on"
},
{
"name":"Retry_Limit",
"value":"False"
},
{
"name":"Type",
"value":"flb_type"
},
{
"name":"Time_Key",
"value":"@timestamp"
},
{
"name":"Logstash_Prefix",
"value":"ks-logstash-log"
},
{
"name":"Match",
"value":"kube.*"
},
{
"name":"Port",
"value":"9200"
},
{
"name":"Host", …
```
> add supports for migrating

- README.md
- config/samples/logging_v1alpha2_fluentbit.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/logging-stack/fluentbitconfig-fluentBitConfig.yaml
- manifests/quick-start/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbitconfig-fluentBitConfig.yaml
> bump fluent bit version to v1.5.0

- docs/user-guides/forwarding-logs-via-http/Dockerfile
- docs/user-guides/forwarding-logs-via-http/README.md
- docs/user-guides/forwarding-logs-via-http/deploy/filter-grep.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/fluentbitconfig-fluentBitConfig.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/input-tail.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/log-generator.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/output-http.yaml
- docs/user-guides/forwarding-logs-via-http/main.go
> add guide for using http output

- docs/user-guides/forwarding-logs-via-http/README.md
- docs/user-guides/forwarding-logs-via-http/deploy/filter-grep.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/input-tail.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/output-http.yaml
> update http output usage guide

- controllers/fluentbitconfig_controller.go
> fix parser is not being watched

- docs/user-guides/forwarding-logs-via-http/Dockerfile
- docs/user-guides/forwarding-logs-via-http/README.md
> fix bug image of example-log-receiver can not run

- api/v1alpha2/fluentbit_types.go
- api/v1alpha2/fluentbitconfig_types.go
- config/crd/bases/logging.kubesphere.io_fluentbitconfigs.yaml
- config/crd/bases/logging.kubesphere.io_fluentbits.yaml
- manifests/setup/fluentbit-operator-crd.yaml
Signed-off-by: daniel-hutao <farmer.hutao@outlook.com>
#40
> Add shortNames for FluentBit FluentBitConfig CRDs

- Makefile
- manifests/setup/fluentbit-operator-deployment.yaml
> init release-0.5

- manifests/setup/kustomization.yaml
This allows easier management via tools that support kustomize, e.g. ArgoCD.
> chore: add kustomize for easier config adjustments

- RELEASE.md
> add release guider

- manifests/logging-stack/fluentbit-fluentBit.yaml
update fluentbit resource，Add request and limits entries
> update fluentbit resource

- CHANGELOG.md
- manifests/setup/fluentbit-operator-deployment.yaml
> Update default version to v0.6.1

- README.md
> Update k8s & kubebuilder dependencies as well as roadmap

- CHANGELOG.md
- Makefile
- manifests/setup/fluentbit-operator-deployment.yaml
Trying to get the `Alias` support out.
Hopefully I get the release process right this time heh.
> init release 0.7.0

- cmd/fluent-bit-watcher/main.go
I think we're seeing possible data race condition in fluent-bit-watcher component where sometimes it does not seem to pick up the change to the config file inside the secret that's reconciled by fluent bit operator.
This attempts to improve the watcher with the following:
- Remove reliance on `timer.Reset()` and `timer.Stop()`. Neither should be used concurrently to other receives from the the timer's channel which the code attempts to do. Instead we create a new timer for each "control" loop iteration that attempts to start + wait + backoff. In addition to a new timer for each backoff, we create a cancellable context, and use the cancel method to trigger the cancellation of the backoff. backoff selects either the backoff timer trigger or the context's done channel event. One will happen …
> fluent-bit-watcher: goroutine synchronization improvements

- api/fluentbitoperator/v1alpha2/filter_types.go
- api/fluentbitoperator/v1alpha2/input_types.go
- api/fluentbitoperator/v1alpha2/output_types.go
- api/fluentbitoperator/v1alpha2/parser_types.go
- manifests/setup/fluentbit-operator-crd.yaml
> fix bug operator may crash when load plugin

- chart/fluentbit-operator/templates/output-elasticsearch.yaml
- chart/fluentbit-operator/templates/output-forward.yaml
- chart/fluentbit-operator/templates/output-kafka.yaml
- chart/fluentbit-operator/values.yaml
Add usage comments for the Output configuration，and the spelling was fixed
> Add comments for output & adjust output switch to enable

- api/fluentbitoperator/v1alpha2/plugins/output/forward_types.go
Signed-off-by: zhu733756 <talonzhu@yunify.com>
- Add logic for forwarding port handling, 
/cc @benjaminhuo @wanjunlei
> Add logic for forwarding port handling

- README.md
> Adjust outline hierarchy

- README.md
> Adjust roadmap

- CHANGELOG.md
- README.md
- RELEASE.md
- VERSION
- chart/fluentbit-operator/Chart.yaml
> update changelog, release, readme

- chart/fluentbit-operator/values.yaml
- config/samples/logging_v1alpha2_fluentbit.yaml
- docs/user-guides/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/quick-start.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
- manifests/setup/fluentbit-operator-deployment.yaml
- manifests/setup/setup.yaml
> change kubespheredev/fluent-bit to kubesphere/fluent-bit

- Makefile
> Fix make manager build cmd

- charts/fluentbit-operator/crds/logging.kubesphere.io_filter.yaml
* fix the logging CRD interval regex in the helm chart
thanks to @wenchajun for spotting: https://github.com/fluent/fluentbit-operator/pull/115#discussion_r687508424
> fix chart throttle.interval regex

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluentbit-operator/Chart.yaml
- charts/fluentbit-operator/values.yaml
- manifests/setup/fluentbit-operator-deployment.yaml
- manifests/setup/setup.yaml
> update the latest release version to release-0.9

- Makefile
> Fix make run

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluentbit-operator/Chart.yaml
- charts/fluentbit-operator/values.yaml
> Init release-0.11

- Makefile
- config/crd/bases/logging.kubesphere.io_fluentbits.yaml
- manifests/setup/fluentbit-operator-crd.yaml
- manifests/setup/setup.yaml
> update crd yaml

- CHANGELOG.md
- README.md
- RELEASE.md
> release 0.12

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluentbit-operator/Chart.yaml
- charts/fluentbit-operator/values.yaml
> update the latest release version to release-0.20

- charts/fluentbit-operator/templates/fluentbit-operator-deployment.yaml
- charts/fluentbit-operator/values.yaml
fix https://github.com/fluent/fluentbit-operator/issues/175
Signed-off-by: chengdehao <dehaocheng@yunify.com>
> Set the crictl  path to a variable

- charts/fluentbit-operator/Chart.yaml
- charts/fluentbit-operator/templates/fluentbit-fluentBit.yaml
- charts/fluentbit-operator/values.yaml
Signed-off-by: Devesh <vrshu112@gmail.com>
> Added secret option to fluentbit depployment in helm chart

- manifests/setup/fluent-operator-deployment.yaml
- manifests/setup/setup.yaml
> fix initcontainer script

- .github/workflows/build-image.yaml
- Makefile
> Add build and push image CI

- .github/workflows/build-op-image.yaml
- README.md
- RELEASE.md
- update RELEASE.md and README.md
> Update README.md and RELEASE.md

- tests/scripts/fluentd_e2e.sh
> fix version changed

- apis/fluentd/v1alpha1/plugins/output/types.go
> Fix fluentd es password

- charts/fluent-operator/templates/fluentd-clusterfluentdconfig.yaml
Signed-off-by: zhu733756 <qq1079333812@gmail.com>
/assign @wenchajun
> add defult clusterfilter selector

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/issue-auto-closer.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- RELEASE.md
- apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
- charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml
- config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
- manifests/setup/fluent-operator-crd.yaml
- manifests/setup/setup.yaml
Fixes #
```release-note
update Release 1.0
```
```docs
```
> update Release 1.0

- .github/workflows/issue-auto-closer.yaml
Fix the bug of feature request issue will closed by mistake.
Fixes #256 
```release-note
None
```
```docs
```
> fix: fix the bug of feature request issue will closed by mistake.

- manifests/quick-start/fluentbit.yaml
Fixes (https://github.com/fluent/fluent-operator/issues/258)
```release-note
```
```docs
```
> fix version error

- apis/fluentbit/v1alpha2/clusterfilter_types_test.go
- apis/fluentbit/v1alpha2/clusterinput_types_test.go
- apis/fluentbit/v1alpha2/clusteroutput_types_test.go
- pkg/utils/utils_test.go
Add utils related unit tests
Resolved part of #220 
```release-note
None
```
```docs
```
> tests: add utils related unit tests

- apis/fluentbit/v1alpha2/clusterfilter_types.go
- apis/fluentbit/v1alpha2/clusterinput_types.go
- apis/fluentbit/v1alpha2/clusteroutput_types.go
- apis/fluentbit/v1alpha2/clusterparser_types.go
- apis/fluentd/v1alpha1/clusterfilter_types.go
- apis/fluentd/v1alpha1/clusteroutput_types.go
- apis/fluentd/v1alpha1/filter_types.go
- apis/fluentd/v1alpha1/output_types.go
- charts/fluent-operator/crds/fluentbit.fluent.io_clusterfilters.yaml
- charts/fluent-operator/crds/fluentbit.fluent.io_clusterinputs.yaml
- charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml
- charts/fluent-operator/crds/fluentbit.fluent.io_clusterparsers.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_clusterfilters.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_filters.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
- config/crd/bases/fluentbit.fluent.io_clusterfilters.yaml
- config/crd/bases/fluentbit.fluent.io_clusterinputs.yaml
- config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
- config/crd/bases/fluentbit.fluent.io_clusterparsers.yaml
- config/crd/bases/fluentd.fluent.io_clusterfilters.yaml
- config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
- config/crd/bases/fluentd.fluent.io_filters.yaml
- config/crd/bases/fluentd.fluent.io_outputs.yaml
- manifests/setup/fluent-operator-crd.yaml
- manifests/setup/setup.yaml
Fixes https://github.com/fluent/fluent-operator/issues/264
```release-note
```
```docs
```
> add its shortname for each CRD

- cmd/fluent-watcher/fluentd/main.go
In fluentd's pod, the config file is a soft link, so fsnotify may not observe the specific operation, so it will not reload the config file.
```release-note
NONE
```
```docs
NONE
```
> fix reload error

- .github/workflows/build-fb-image.yaml
- CHANGELOG.md
- Makefile
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
Fixes #
```release-note
release-1.0.1-rc
```
```docs
```
> Update fluentbit version and release-1.0.1-rc

- .github/workflows/build-fb-image.yaml
- CHANGELOG.md
- Makefile
- RELEASE.md
- charts/fluent-operator/templates/fluent-operator-deployment.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
Fixes #
```release-note
release 1.0.1
```
```docs
```
> Release 1.0.1

- cmd/fluent-watcher/fluentd/main.go
Fixes #
```release-note
```
```docs
```
> change kill signal

- README.md
Correct typos in the readme 
Adjust layout
Fixes #
```release-note
```
```docs
```
> Correct typos & adjust layout

- CHANGELOG.md
- Makefile
- charts/fluent-operator/values.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
release1.0
```
```docs
```
> change fluentbit version

- apis/fluentd/v1alpha1/plugins/output/opensearch.go
- apis/fluentd/v1alpha1/plugins/output/types.go
- apis/fluentd/v1alpha1/plugins/params/const.go
- apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-opensearch.cfg
- apis/fluentd/v1alpha1/tests/expected/fluentd-mixed-cfgs-output-opensearch.cfg
- apis/fluentd/v1alpha1/tests/expected/fluentd-namespaced-cfg-output-opensearch.cfg
- apis/fluentd/v1alpha1/tests/helper_test.go
- apis/fluentd/v1alpha1/tests/tools.go
- charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
- charts/fluent-operator/templates/fluentd-output-opensearch.yaml
- cmd/fluent-watcher/fluentd/Dockerfile.amd64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64.base
- cmd/fluent-watcher/fluentd/base/Dockerfile
- config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
- config/crd/bases/fluentd.fluent.io_outputs.yaml
- docs/plugins/fluentd/index.md
- docs/plugins/fluentd/output/opensearch.md
- docs/plugins/fluentd/output/types.md
- manifests/setup/fluent-operator-crd.yaml
- manifests/setup/setup.yaml
Signed-off-by: jett-deng <dengtian1997@outlook.com>
Fluentd integrate OpenSearch plugin
Fixes #285 
```release-note
none
```
```docs
none
```
> Fluentd integrate OpenSearch plugin

- .github/workflows/build-fb-image.yaml
- .github/workflows/build-fd-image.yaml
- .github/workflows/build-op-image.yaml
- .github/workflows/main.yaml
- cmd/fluent-watcher/fluentd/Dockerfile.amd64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64.quick
In the previous commit, the `alpine` image version was upgraded, resulting in some plugin versions not matching the system version and thus the build failed. We should refer to the official dockerfile of fluent.
https://github.com/fluent/fluentd-docker-image/blob/master/v1.14/alpine/Dockerfile
Fixes #
```release-note
```
```docs
```
> fix github action build

- .github/workflows/build-fb-image.yaml
- CHANGELOG.md
- Makefile
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> release-1.1.0

- CHANGELOG.md
Fixes #
```release-note
```
```docs
```
> fix wrong date

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/request_help.yaml
Simplify the step of issue report, and more please see #328
Fixes #328
```release-note
None
```
```docs
```
> fix: simplify the step of issue report

- README.md
- docs/plugins/fluentbit/index.md
Update the index of plugins for fluent-bit
Fixes #
```release-note
None
```
```docs
```
> docs: update the index of plugins for fluent-bit

- apis/fluentbit/v1alpha2/plugins/custom/custom_types.go
- apis/fluentbit/v1alpha2/plugins/params/kvs.go
Signed-off-by: Gentleelephant <birdhk@kubesphere.io>
Optimize the code
Fixes #
```release-note
```
```docs
```
> perf: optimize code

- .github/workflows/build-fb-image.yaml
- CHANGELOG.md
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
none
```
```docs
```
> update fluentbit to v1.9.8

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
none
```
```docs
```
> Upgrade fluentbit to v1.9.9

- CHANGELOG.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
Fixes #
```release-note
v1.5.1
```
```docs
```
> releasev1.5.1

- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentd/Dockerfile.amd64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64.quick
Signed-off-by: Gentleelephant <birdhk@kubesphere.io>
Fixes #
```release-note
```
```docs
```
> upgrade golang image version

- charts/fluent-operator/values.yaml
- manifests/setup/fluent-operator-deployment.yaml
- manifests/setup/setup.yaml
Signed-off-by: Gentleelephant <birdhk@kubesphere.io>
Fixes #
```release-note
```
```docs
```
> upgrade docker image version

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
Fixes #
```release-note
release 1.6.0
```
```docs
```
> release 1.6.0

- cmd/fluent-manager/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentd/Dockerfile.amd64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64
- cmd/fluent-watcher/fluentd/Dockerfile.arm64.quick
- docs/best-practice/forwarding-logs-via-http/Dockerfile
Reverts fluent/fluent-operator#416
> Revert "build: Enhance binary"

- CHANGELOG.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
Fixes #
```release-note
release 1.6.1
```
```docs
```
> release 1.6.1

- CHANGELOG.md
Fixes #
```release-note
release 1.7.0
```
```docs
```
> release 1.7.0

- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
Fixes #495 
```release-note
Increase operator memory limit to 60Mi
```
```docs
```
> Increase operator memory limit to 60Mi

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
Upgrade fluent-bit to v2.0.8
```
```docs
```
> Fluent-bit upgrade to v2.0.8

- .github/workflows/main.yaml
Fixes #
```release-note
```
```docs
```
> Change helm e2e test timeout to 60 minutes

- tests/scripts/fluentd_helm_e2e.sh
Fixes #
```release-note
```
```docs
```
> Change cleanup script for to avoid helm e2e test fail

- .github/workflows/main.yaml
Reverts fluent/fluent-operator#532
> Revert "Change helm e2e test timeout to 60 minutes"

- tests/scripts/fluentd_e2e.sh
- tests/scripts/fluentd_helm_e2e.sh
Fixes #
```release-note
```
```docs
```
> Refine e2e test script

- tests/scripts/fluentd_helm_e2e.sh
Fixes #
```release-note
```
```docs
```
> Fix error in helm e2e

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
Fixes #
```release-note
release 2.0
```
```docs
```
> release 2.0

- CHANGELOG.md
- RELEASE.md
Fixes #
```release-note
v2.0.0
```
```docs
```
> Change the release date

- manifests/setup/setup.yaml
Fixes #
```release-note
release-2.0
```
```docs
```
> release-2.0

- .github/workflows/build-fb-image.yaml
- .github/workflows/build-fd-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentd/Dockerfile.arm64.base
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Upgrade Fluentbit to v2.0.9

- CHANGELOG.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
Fixes #
```release-note
```
```docs
```
> release-2.0.1

- Makefile
- cmd/fluent-manager/Dockerfile
Signed-off-by: fengshunli <1171313930@qq.com>
Fixes #
```release-note
```
```docs
```
> Support multi-architecture compilation, add platform amd64 compilation

- Makefile
Fixes #
```release-note
```
```docs
```
> Bump kustomize from 4.5.7 to 5.0.0

- cmd/fluent-watcher/fluentbit/Dockerfile
Reverts fluent/fluent-operator#570
> Revert "build(deps): Bump golang from 1.19.5-alpine3.16 to 1.20.1-alpine3.16 in /cmd/fluent-watcher/fluentbit"

- apis/fluentd/v1alpha1/plugins/common/buffer_types.go
- charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
- config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
- config/crd/bases/fluentd.fluent.io_outputs.yaml
- manifests/setup/fluent-operator-crd.yaml
- manifests/setup/setup.yaml
Fixes #581 
```release-note
None
```
```docs
```
> Fixes #581 Path not required

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
Fixes #
```release-note
2.1.0
```
```docs
```
> release2.1.0

- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
Fixing some helm chart lint errors. At the request of @benjaminhuo 
Fixes [fluent/helm-charts/#327](https://github.com/fluent/helm-charts/pull/327)
```release-note
None
```
```docs
```
> Fix helm chart lint errors

- .github/workflows/lint-test.yaml
- charts/ct.yaml
Fixes #
```release-note
```
```docs
```
> Add charts test

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Upgrade fluent-bit to v2.0.10

- README.md
This PR extends the README with documentation about [disabling unused controllers and crds](https://github.com/fluent/fluent-operator/pull/621) feature.
Fixes #
> Explain how to disable component controllers in the README

- README.md
Fixes #
```release-note
```
```docs
```
> update README to mention new namespace FluentBit CRDs

- .github/workflows/build-fb-image.yaml
- Makefile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
Fixes https://github.com/fluent/fluent-operator/issues/459
```release-note
Automatic pushing of fluentbit-debug version images
```
```docs
```
> Automatic pushing of fluentbit-debug version images

- .github/workflows/main.yaml
Fixes #
```release-note
```
```docs
```
> update github runner to ubuntu 22.04

- apis/fluentbit/v1alpha2/clusterfilter_types_test.go
- apis/fluentbit/v1alpha2/plugins/filter/modify_types_test.go
- apis/fluentbit/v1alpha2/plugins/output/datadog_types_test.go
Fixes #
```release-note
```
```docs
```
> Fixing unit testing bugs

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Fluent-bit upgrade to v2.0.11

- apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
Fixes https://github.com/fluent/fluent-operator/issues/685
```release-note
```
```docs
```
> Fix null pointer error

- .github/dependabot.yml
Fixes #
```release-note
```
```docs
```
> Adjust fluentd watcher dependabot

- .github/workflows/build-fd-image.yaml
Fixes #
```release-note
```
```docs
```
> Adjust fluentd arm64 image build timeout

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
Fluent-bit upgrade to v2.1.2
```
```docs
```
> Fluent-bit upgrade to v2.1.2

- charts/fluent-operator/templates/fluentbit-input-node-exporter-metrics-edge.yaml
- charts/fluent-operator/templates/fluentbit-input-prometheus-scrape-metrics-edge.yaml
- charts/fluent-operator/templates/fluentbit-output-prometheus-remote-write-edge.yaml
- manifests/kubeedge/input-node-exporter-metrics-edge.yaml
- manifests/kubeedge/input-prometheus-scrape-metrics-edge.yaml
- manifests/kubeedge/output-prometheus-remote-write-edge.yaml
- manifests/kubeedge/output-stdout-edge.yaml
Adjust edge metrics config
Fixes #
```release-note
None
```
```docs
```
> Adjust edge metrics collection config

- controllers/fluentbitconfig_controller.go
Fixes #747 
```release-note
```
```docs
```
> fluentbit namespace-logging: only generate rewrite tag config once

- apis/fluentbit/v1alpha2/clusteroutput_types.go
- apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
Fixes #
```release-note
None
```
```docs
```
> minor typo fix for firehose

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Fluent-bit upgrade to v2.1.4

- CHANGELOG.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #
```release-note
release 2.3.0
```
```docs
```
> release 2.3.0

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Fluent-bit upgrade to v2.1.6

- CHANGELOG.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #
```release-note
release 2.4.0
```
```docs
```
> release 2.4.0

- charts/fluent-operator/templates/fluentbit-fluentBit.yaml
> add  hostNetwork option

- charts/fluent-operator/templates/fluentbit-fluentBit.yaml
Allows setting dnsPolicy for fluentbit in helm chart
> feat(helm): allow setting dnsPolicy for fluentbit

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Bump fluentbit to 2.1.10

- apis/fluentd/v1alpha1/plugins/common/parse_types.go
fix fluentd parser plugin parameter keep_time_key
Fixes #
```release-note
None
```
```docs
```
> fix: fix fluentd parser keep_time_key

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> Bump fluentbit to 2.2.0

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #
```release-note
2.6.0
```
```docs
```
> release 2.6.0

- charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusterinputs.yaml
- charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_inputs.yaml
- config/crd/bases/fluentd.fluent.io_clusterinputs.yaml
- config/crd/bases/fluentd.fluent.io_inputs.yaml
- docs/plugins/fluentd/input/types.md
Fixes #1020 
```release-note
None
```
```docs
```
> fix: missing CRD entries and documentation #1020

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #
```release-note
release 2.7.0
```
```docs
```
> release-2.7.0

- charts/fluent-operator/templates/fluentbit-output-prometheus-remote-write-edge.yaml
fix prometheus-remote-write-edge templates error
Fixes #
```release-note
```
```docs
```
> fix prometheus-remote-write-edge templates error

- apis/fluentd/v1alpha1/plugins/output/s3.go
- apis/fluentd/v1alpha1/plugins/output/types.go
- charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
- charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
- config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
- config/crd/bases/fluentd.fluent.io_outputs.yaml
- docs/plugins/fluentd/output/s3.md
- go.mod
- go.sum
- manifests/setup/fluent-operator-crd.yaml
- manifests/setup/setup.yaml
Fixes #1037
```release-note
None
```
```docs
```
> feat: support s3 server side encryption

- .github/workflows/build-fb-image.yaml
- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
What the title says, really.
Fixes #
```release-note
Bump fluent-bit to 2.2.2.
```
```docs
```
> Bump fluent-bit to 2.2.2

- apis/fluentd/v1alpha1/plugins/common/buffer_types.go
- apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-memory-buffer.cfg
- apis/fluentd/v1alpha1/tests/helper_test.go
- apis/fluentd/v1alpha1/tests/tools.go
Fixes #1103 
```release-note
None
```
```docs
```
> fix: no Path default value for memory buffer #1103

- apis/fluentd/v1alpha1/tests/helper_test.go
This PR delete remaining traces in code
```release-note
```
```docs
```
> fix: delete remaining debug traces

- CHANGELOG.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #
```release-note
None
```
```docs
None
```
> release-2.7.1

- Makefile
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- config/samples/fluentbit_v1alpha2_fluentbit.yaml
- docs/best-practice/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Upgrades to upstream fluent-bit version 3.0.4
Fixes #1175
```release-note
Upgrade fluent-bit to version 3.0.4 addressing CVE-2024-4323
```
```docs
```
> Upgrade fluent-bit to 3.0.4

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #
```release-note
```
```docs
```
> release 2.9.0

- charts/fluent-operator/templates/fluentbit-servicemonitor.yaml
- charts/fluent-operator/values.yaml
Fixes #1130 
```release-note
Add ServiceMonitor template to allow user to custom the values.
```
```docs
```
> Templatize ServiceMonitor

- .github/workflows/build-fb-image.yaml
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
- charts/fluent-operator/values.yaml
- cmd/fluent-watcher/fluentbit/Dockerfile
- cmd/fluent-watcher/fluentbit/Dockerfile.debug
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
> update fluentbit to v3.1.0

- charts/fluent-operator/templates/fluentbit-output-loki.yaml
Fixes #1247
```release-note
None
```
```docs
```
> Fix release name on fluentbit output loki

- .github/workflows/build-fb-image.yaml
- charts/fluent-operator/values.yaml
- manifests/kubeedge/fluentbit-fluentbit-edge.yaml
- manifests/logging-stack/fluentbit-fluentBit.yaml
- manifests/quick-start/fluentbit.yaml
- manifests/regex-parser/fluentbit-fluentBit.yaml
Fixes #
```release-note
```
```docs
```
Dockerfile has been updated in https://github.com/fluent/fluent-operator/pull/1266
> update fluentbit to v3.1.4

- cmd/fluent-manager/main.go
Fixes #1333
```release-note
None
```
```docs
```
> fix assignment to entry in nil map when --watch-namespaces flag is provided

- apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
- apis/fluentbit/v1alpha2/plugins/filter/lua_types.go
- controllers/fluentbitconfig_controller.go
Fixes #1339
```release-note
```
```docs
```
> feat: support lua filter in namespaced CRD

- charts/fluent-operator/templates/fluentbit-fluentBit.yaml
Fixes 1: This fixes the indentation bug introduced in the earlier PR : https://github.com/fluent/fluent-operator/pull/1320
```release-note
None
```
```docs
None
```
> Fix indentation bug

- .github/workflows/bump-fluent-bit-version.yaml
- RELEASE.md
Add documents for automation pipelines
Fixes #
```release-note
```
```docs
```
> feat: improve pipelines and add documents

- apis/fluentd/v1alpha1/plugins/output/types.go
I believe this https://github.com/fluent/fluent-operator/pull/1169 is incomplete, those options never land in the actual secret.
Fixes #
```release-note
```
```docs
```
> fix: missing cloudAuth/cloudId pair inserts

- charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml
- charts/fluent-operator/templates/fluentbitconfig-fluentbitconfig-edge.yaml
- charts/fluent-operator/values.yaml
> Support setting configFileFormat in helmchart

- CHANGELOG.md
- README.md
- RELEASE.md
- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
- charts/fluent-operator/charts/fluentd-crds/Chart.yaml
Fixes #1479
```release-note
```
```docs
```
> feat: release 3.3.0

- .github/workflows/release-tool.yaml
fix the release-tool pipeline, add signoff
Fixes #
```release-note
```
```docs
```
> fix: add signoff to release pr

- cmd/fluent-watcher/fluentbit/main.go
Fixes #1496
```release-note
```
```docs
```
> chore: update watcher start log

- .github/dependabot.yml
Signed-off-by: Marco Franssen <marco.franssen@gmail.com>
> dependabot: Refactor docker ecosystem to new syntax

- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/templates/fluentd-fluentd.yaml
Fixes https://github.com/fluent/helm-charts/issues/617
```release-note
None
```
```docs
```
>  fix: Invalid reference

- go.mod
Fixes #1660
```release-note
```
```docs
```
> build(deps): bump golang to 1.24.5
