fluent/fluent-operator

cmd/fluentbit-operator/fluentbit/fluentbit.go

Starting from Kubernetes v1.16, DaemonSet resources are no longer served from extensions/v1beta .

update ds apiVersion

---

controllers/fluentbitconfig_controller.go

The bug is that FluentBitConfig controller will generate config files for every custom resource it is watching (FluentBitConfig, Input, Filter, Output). This causes unnecessary creation of config files, like the red rectangle shows.
The correct way is to generate config file based on FluentBitConfig resource only, like the yellow arrow points out.

fix FluentBitConfig controller generates redundant config files

---

docs/user-guides/forwarding-logs-via-http/README.md
docs/user-guides/forwarding-logs-via-http/kubesphere/filter-grep.yaml
docs/user-guides/forwarding-logs-via-http/kubesphere/input-tail.yaml
docs/user-guides/forwarding-logs-via-http/kubesphere/output-http.yaml

Add YAML templates for http demo.
Now, for KubeSphere users who have enabled logging, they can simply apply these YAML files in the folder `kubesphere`. The only effort required by users is to modify output host (`log-receiver.default.svc` by default) and port (`8080` by default) as per their own setup.

add yaml templates for http demo

---

README.md
manifests/logging-stack/auditd/auditd-lua-config.yaml
manifests/logging-stack/auditd/filter-auditd.yaml
manifests/logging-stack/auditd/input-auditd.yaml
manifests/logging-stack/auditd/output-auditd-elasticsearch.yaml
pkg/operator/daemonset.go

support for audit logs

---

docs/user-guides/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit-fluentBit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

I have updated Fluent-bit to v1.7.3 in the Kubesphere cluster, and the cluster is running fine. Below are the screenshots of the cluster running.

update fluent-bit images

---

CHANGELOG.md
Makefile
RELEASE.md
manifests/setup/fluentbit-operator-deployment.yaml

Hello, 
Just wanted to get the discussion started for cutting a new release to include changes since 0.5: #49, #50, and #51. I am not sure what the process is exactly... There was PR #47 for 0.5, but that went to `release-0.5` branch... So I imagine this should go into `release-0.6` branch that someone should create? Anyway just looking for guidance and to get the process going for a release if it's agreeable with everyone to publish a new release. Thanks.

init release-0.6

---

api/fluentbitoperator/v1alpha2/input_types.go
api/fluentbitoperator/v1alpha2/output_types.go
config/crd/bases/logging.kubesphere.io_inputs.yaml
config/crd/bases/logging.kubesphere.io_outputs.yaml
manifests/setup/fluentbit-operator-crd.yaml

This PR adds support for [Alias property](https://docs.fluentbit.io/manual/administration/monitoring#configuring-aliases) of Input and Output plugin specs, as these can be useful for monitoring purposes.

add support for plugin alias property in input and output specs

---

manifests/setup/fluentbit-operator-deployment.yaml

[As per comment](https://github.com/kubesphere/fluentbit-operator/pull/70#issuecomment-870425610) in #70, updating the deployment tag to tag `v0.7.0` in master branch.

update deployment tag to v0.7.0

---

config/samples/logging_v1alpha2_fluentbit.yaml
config/samples/logging_v1alpha2_input.yaml
docs/user-guides/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
docs/user-guides/forwarding-logs-via-http/deploy/input-tail.yaml
manifests/logging-stack/auditd/input-auditd.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/logging-stack/input-systemd-docker.yaml
manifests/logging-stack/input-systemd-kubelet.yaml
manifests/logging-stack/input-tail.yaml
manifests/regex-parser/input-tail.yaml

Signed-off-by: wenchajun <995729579@qq.com>
add hostPath config configuration.
In default mode, log loss occurs if FluentBit POD is removed during log generation. 
You can modify the input.spec.dbSync and input.spec.refreshIntervalSeconds fields for better performance. However, log generation is slightly faster,it is still possible to lose a small number of logs.
- input.spec.dbSync: FULL
When synchronous is FULL, the SQLite database engine will use the xSync method of the VFS to ensure that all content is safely written to the disk surface prior to continuing. This ensures that an operating system crash or power failure will not corrupt the database. FULL synchronous is very safe, but it is also slower.

add hostpath

---

CHANGELOG.md
docs/plugins/input/dummy.md
manifests/setup/fluentbit-operator-deployment.yaml
manifests/setup/setup.yaml

Just some cleanup to bring in latest 0.7 changes into master...
- Updates `dummy` plugin docs.
- Updates changelog.
- Updates the image used in manifests to `v0.7.1` tag.

update changelog, dummy docs, and image version in manifests

---

chart/fluentbit-operator/templates/fluentbit-fluentBit.yaml
chart/fluentbit-operator/templates/fluentbit-operator-deployment.yaml
chart/fluentbit-operator/values.yaml

in the current version, This is using the hardcoded values of resources here in this file. Calling the values of `resources` defined on the values.yaml file to the `fluentbit-operator-deployment.yaml`

added support to use resources defined in values file

---

cmd/fluent-bit-watcher/main.go

Signed-off-by: wenchajun <dehaocheng@yunify.com>
The SIGTERM signal is a generic signal used to cause program termination. Unlike SIGKILL, this signal can be blocked, handled, and ignored. It is the normal way to politely ask a program to terminate.

Fix log loss bug

---

chart/fluentbit-operator/templates/fluentbit-operator-deployment.yaml
chart/fluentbit-operator/values.yaml

in fluentbit-operator deployment file, there was no support for the imagePullSecrets though it was available in values.yaml file. I will add in other templates also

Added support to use imagePullSecrets defined in values.yaml file for operator

---

api/fluentbitoperator/v1alpha2/doc.go
api/generated/clientset/versioned/clientset.go
api/generated/clientset/versioned/fake/clientset_generated.go
api/generated/clientset/versioned/fake/register.go
api/generated/clientset/versioned/scheme/register.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_filter.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_fluentbit.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_fluentbitconfig.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_fluentbitoperator_client.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_input.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_output.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_parser.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/filter.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fluentbit.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fluentbitconfig.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fluentbitoperator_client.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/input.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/output.go
api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/parser.go

While the current implementation of go client generation introduced in #51 seems to work in production fine, there appears to be issues when attempting to use the generated fake package. The issue arises with defaulting to groupName taken from package `fluentbitoperator`, which results in the fake package defining resource [types with that group name](https://github.com/kubesphere/fluentbit-operator/blob/master/api/generated/clientset/versioned/typed/fluentbitoperator/v1alpha2/fake/fake_input.go#L37):
```go
var inputsResource = schema.GroupVersionResource{Group: "fluentbitoperator", Version: "v1alpha2", Resource: "inputs"}
var inputsKind = schema.GroupVersionKind{Group: "fluentbitoperator", Version: "v1alpha2", Kind: "Input"}
```
The problem can be simply reproduced by doing something …

update groupname for client-gen to logging.kubesphere.io

---

README.md
manifests/logging-stack/auditd/kustomization.yaml
manifests/logging-stack/kustomization.yaml
manifests/setup/kustomization.yaml

Add kustomize file

---

README.md
cmd/manager/main.go
config/rbac/role.yaml
controllers/fluentbit_controller.go
manifests/setup/fluentbit-operator-clusterRole.yaml
manifests/setup/setup.yaml
pkg/operator/daemonset.go

* Adds `--watch-namespaces` command line argument to operator; if provided it only watches for resources in the specified namespaces
* Updates fluentbit RBAC from cluster scoped to namespace scoped

Optional watch-namespaces for controller manager

---

api/fluentbitoperator/v1alpha2/fluentbit_types.go
cmd/fluent-bit-watcher/Dockerfile
cmd/fluent-bit-watcher/main.go
config/crd/bases/logging.kubesphere.io_fluentbits.yaml
manifests/setup/fluentbit-operator-crd.yaml
manifests/setup/setup.yaml
pkg/filenotify/filenotify.go
pkg/filenotify/fsnotify.go
pkg/filenotify/poller.go
pkg/operator/daemonset.go

[github.com/fsnotify/fsnotify](https://github.com/fsnotify/fsnotify) uses ionotify as the mechanism to detect for changes in the watched file system.
Within sandboxed or restricted environment contexts (such as [gVisor](https://gvisor.dev/)), certain system calls may be prohibited under some specific scenarios. 
This means that currently the `fluent-bit-watcher` component cannot be used in sandboxed environment properly. The changes to the underlying Fluent Bit config file (mounted from the `fluentbit-operator` secret) will not be detected properly, and fluent bit process will not be restarted when changes occur.
One approach to work around such issue is to watch files utilizing stat polling. Ideally fsnotify will support polling. There is an [existing long standing …

Add support for polling watcher

---

charts/fluentbit-operator/templates/fluentbit-operator-clusterRole.yaml
config/rbac/role.yaml
controllers/fluentbit_controller.go
manifests/setup/fluentbit-operator-clusterRole.yaml
pkg/operator/daemonset.go

If Fluentbit has role permissions, it can only access the namespace to which it belongs. Some plug-ins do not work properly, so Fluentbit should have ClusterRole permissions.
/cc @wanjunlei  @benjaminhuo 
Signed-off-by: wenchajun <dehaocheng@yunify.com>

Expand fluetnbit permissions

---

README.md
charts/fluentbit-operator/templates/fluentbit-operator-deployment.yaml
charts/fluentbit-operator/templates/input-systemd-container.yaml
charts/fluentbit-operator/templates/input-tail.yaml
charts/fluentbit-operator/templates/output-elasticsearch.yaml
charts/fluentbit-operator/values.yaml
manifests/logging-stack/output-elasticsearch.yaml

Collect service logs for different container runtime
Signed-off-by: wenchajun <dehaocheng@yunify.com>

collect service log

---

api/fluentbitoperator/v1alpha2/plugins/output/elasticsearch_types.go

Signed-off-by: dkeven <keven@kubesphere.io>
When generating params from the `Elasticsearch` type, in:
https://github.com/fluent/fluentbit-operator/blob/4b96fcc0a7e19a5bb89f7051982d7bcee538b2a2/api/fluentbitoperator/v1alpha2/plugins/output/elasticsearch_types.go#L155-L159
,the config keys of the `Type` and `Index` fields are incorrectly set to `Host` if they are not empty, resulting in an overwriting of the true `Host` config, like in this issue: https://github.com/kubesphere/kubesphere/issues/4395

Fix the incorrect keys of the es output plugin

---

.github/workflows/main.yaml
api/fluentbitoperator/v1alpha2/plugins/input/tail_types.go
conf/parsers.conf
config/crd/bases/logging.kubesphere.io_inputs.yaml
manifests/setup/fluentbit-operator-crd.yaml
manifests/setup/setup.yaml

https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-and-containers-v1.8
If you are running Fluent Bit to process logs coming from containers like Docker or CRI, you can use the new built-in modes for such purposes. This will help to reassembly multiline messages originally split by Docker or CRI:
```
[INPUT]
name              tail
path              /var/log/containers/*.log
multiline.parser  docker, cri
```
Signed-off-by: chengdehao <dehaocheng@yunify.com>

tail new multiline support(fluentbit must be later than V1.8)

---

apis/fluentd/v1alpha1/fluentd_types.go
apis/fluentd/v1alpha1/helper.go
apis/fluentd/v1alpha1/helper_test.go
apis/fluentd/v1alpha1/plugins/common/buffer_types.go
apis/fluentd/v1alpha1/plugins/common/match_types.go
apis/fluentd/v1alpha1/plugins/filter/types.go
apis/fluentd/v1alpha1/plugins/output/types.go
apis/fluentd/v1alpha1/plugins/params/const.go
apis/fluentd/v1alpha1/plugins/params/model.go
apis/fluentd/v1alpha1/tests/expected-main-cfgs.cfg
apis/fluentd/v1alpha1/zz_generated.deepcopy.go
cmd/fluent-manager/main.go
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
controllers/fluent_controller_finalizer.go
controllers/fluentd_controller.go
controllers/fluentdconfig_controller.go
manifests/forward/fluentd-cluster-cfg-output-buffer-example.yaml
manifests/forward/fluentd-cluster-cfg-output-es.yaml
manifests/forward/fluentd-cluster-cfg-output-kafka.yaml
manifests/forward/fluentd-mixed-cfgs-output-es.yaml
manifests/forward/fluentd-namespaced-cfg-output-es.yaml
manifests/quick-start/fluentd-http.yaml
manifests/setup/fluent-operator-clusterRole.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/service.go
pkg/operator/sts.go

Points:
-  convert deployment to sts
-  add fluentd examples
This pr needs to be merged before #192

Add fluentd examples

---

manifests/setup/fluent-operator-deployment.yaml
manifests/setup/setup.yaml

If the target path is unmouted, this script would be panic. Like the platform Kind.
Fix like the commit described.

Fix initcontainer script

---

README.md
charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/templates/fluentbir-clusterinput-systemd-container.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-containerd.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-kubernetes.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-systemd.yaml
charts/fluent-operator/templates/fluentbit-clusterinput-systemd-kubelet.yaml
charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml
charts/fluent-operator/templates/fluentbit-containerd-config.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/templates/fluentbit-lua-config.yaml
charts/fluent-operator/templates/fluentbit-output-elasticsearch.yaml
charts/fluent-operator/templates/fluentbit-output-forward.yaml
charts/fluent-operator/templates/fluentbit-output-kafka.yaml
charts/fluent-operator/templates/fluentd-clusterfluentdconfig.yaml
charts/fluent-operator/templates/fluentd-filter-kafka.yaml
charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/templates/fluentd-fluentdconfig.yaml
charts/fluent-operator/templates/fluentd-output-elasticsearch.yaml
charts/fluent-operator/templates/fluentd-output-kafka.yaml
charts/fluent-operator/values.yaml
manifests/setup/fluent-operator-deployment.yaml

Signed-off-by: chengdehao <wenchajun@gmail.com>

Optimize the helm chart

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/issue-auto-closer.yaml
CONTRIBUTING.md

Add CI templates for fluentbit-operator.
Fixes #207
```release-note
None
```
```docs
- [Other doc]: https://github.com/fluent/fluent-operator/pull/242
```

feat: Add CI templates for fluent-operator

---

apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #
```release-note
```
```docs
```

fix fluentbit operator not support Time_Key_Nanos field bug

---

charts/fluent-operator/templates/fluentbit-output-elasticsearch.yaml
charts/fluent-operator/values.yaml

Support `logstashPrefix`, `httpUser` and so on to ClusterOutput.
Fixes #265
```release-note
Added logstashPrefix, httpUser, tls to ClusterOutput.
```
```docs
```

feature: support `logstashPrefix` to ClusterOutput

---

charts/fluent-operator/templates/fluentd-fluentd.yaml

Signed-off-by: hostalp [hostalp@post.cz](mailto:hostalp@post.cz)
Fixes the Helm chart for Fluentd resources settings, where Fluentbit resource settings were incorrectly used instead.
Fixes #271
None

fix: Helm Chart for Fluentd resources settings (#271)

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml

Fixes init container crash when using crio container runtime.
Fixes #259 
```release-note
None
```
```docs
```

Fix crio init container mount path

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/request_help.yaml
.github/workflows/issue-auto-closer.yaml

Fix the bug of feature help issue will be closed by mistake.
Fixes #
```release-note
None
```
```docs
```

fix: the issue of request help closed by mistake

---

Makefile
apis/fluentd/v1alpha1/plugins/output/loki.go
apis/fluentd/v1alpha1/plugins/output/types.go
apis/fluentd/v1alpha1/plugins/params/const.go
apis/fluentd/v1alpha1/plugins/tls_types.go
apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-loki.cfg
apis/fluentd/v1alpha1/tests/helper_test.go
apis/fluentd/v1alpha1/tests/tools.go
charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
cmd/fluent-watcher/fluentd/Dockerfile.amd64
cmd/fluent-watcher/fluentd/base/Dockerfile
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #310 
```release-note
None
```
```docs
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
name: fluentd-output-loki
labels:
output.fluentd.fluent.io/enabled: "true"
spec: 
outputs: 
- loki:
host: loki-logging-data.kubesphere-logging-system.svc
port: 3100
```

feat(plugin): support fluentd loki output

---

apis/fluentd/v1alpha1/plugins/output/loki.go
docs/plugins/fluentd/index.md
docs/plugins/fluentd/output/loki.md
docs/plugins/fluentd/tls.md

Update the fluentd loki output documentation. Refer to #346 
None
```release-note
None
```
```docs
None
```

add fluentd loki output documentation

---

charts/fluent-operator/values.yaml
docs/plugins/fluentbit/clusterinput/node-exporter-metrics.md

Add docs to the node exporter metrics plugin
Fixes #
```release-note
None
```
```docs
```

Add guide for node exporter metrics plugin

---

controllers/fluentdconfig_controller.go

Fixes https://github.com/fluent/fluent-operator/issues/305
```release-note
None
```
```docs
```

non-kubernetes format

---

apis/fluentbit/v1alpha2/clusteroutput_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR is in relation to the recently merged PR https://github.com/fluent/fluent-operator/pull/417 . This PR does nothing put fixing a simple typo.
This PR fixes a typo in the recent PR https://github.com/fluent/fluent-operator/pull/417 . 
Some comments used the term 'Spklunk' but it should have been 'Splunk'.
This PR should not, add remove or change any functionality. It is purely cosmetic.
Fixes #
```release-note
None
```
```docs
```

fixing a typo 'Spklunk' to 'Splunk'

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml

Fixes error in version 1.5.1 where setting Kubernetes: true breaks the install of fluentbit
Fixes #421
no

Fixing error in fluentbit-FluentBit

---

apis/fluentbit/v1alpha2/plugins/parser/regex_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusterparsers.yaml
config/crd/bases/fluentbit.fluent.io_clusterparsers.yaml
docs/plugins/fluentbit/clusterparser/regex.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Adds support to define Time_Offset parameter on regex parser
Fixes #
```release-note
```
```docs
```

Added support for Time_Offset parameter in regex parser

---

README.md

fix clusterParser to ClusterParser in README
Fixes #
```release-note
None
```
```docs
```

fix clusterParser to ClusterParser

---

apis/fluentbit/v1alpha2/plugins/output/splunk_types.go

This PR fixes `nil` pointer exceptions while rendering fluentbit config, when Splunk `ClusterOutput` does not define boolean attributes.
It was fixed by intention in a way to explicitly show `Off` values when the respective boolean attributes are explicitly defined in the `ClusterOutput` definition, despite the fact that `Off` might be the default value when not provided.
It is confirmed working, locally, now.
Fixes #
no issue raised, yet, as the Splunk output was contributed by 'us' and there was no fluent-operator release for that, yet.
```release-note
None
```
```docs
```

fix: handling optional bool parameters for Splunk ClusterOutput

---

apis/fluentbit/v1alpha2/plugins/output/splunk_types.go

This PR adds missing config attributes for splunk output to be rendered to the configuration. We just missed it in previous PRs
Fixes - no issue raised for this.
```release-note
None
```
```docs
```

fix: add missing config attributes for splunk output

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml

Signed-off-by: Jeremiah Roth <jeremiah@sundeck.io>
Fixes template render error in fluentbit-fluentBit.yaml when adding more than one annotation, secret, volume, volumeMount.
Fixes #457
```release-note
None
```
```docs
```

fix: fluentbit template render error - fixes #457

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml

I created this PR because I was struggling to add (multiple) annotations to my fluent-bits. I noticed that this code ( https://github.com/fluent/fluent-operator/blob/0ca8da204eb4dd249f90b39201aebdc3e97923fb/charts/fluent-operator/templates/fluentbit-fluentBit.yaml#L43 ) is the problem. To my understanding if multiple annotations are supplied through the values, it will generate output such as this:
```
annotations:
key0: value0
key1: value1
key2: value2
```
Note that there are 6 spaces before key0 and only 4 spaces before key1 and key2.
The above issue only manifests if multiple annotations are supplied. If one only key0 and value0 are supplied it will work just fine as all keys and values and are intended the same way but as soon as there is more than one key/value pair. key-pair one …

fix: intendation corrected in fluentbit-fluentBit.yaml

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-containerd.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-kubernetes.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-systemd.yaml
charts/fluent-operator/templates/fluentbit-containerd-config.yaml
charts/fluent-operator/values.yaml

Allows users to control and slightly configure the deployment of default ClusterFilters, this is useful for when users have their own ClusterFilter being deployed which overlaps with the defaults.
Fixes #
```release-note
New values defined to allow users to control the deployment of the default ClusterFilters.
The default values match the existing behaviour today.
fluentbit:
filter:
kubernetes:
enable: true
labels: false
annotations: false
containerd:
enable: true
systemd:
enable: true
```
```docs
```

feat: control/configure default ClusterFilters (helm chart)

---

apis/fluentbit/v1alpha2/fluentbit_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/daemonset.go

Adds more configurations in the fluent-bit Daemonset.  In this way, FB becomes more extensible and flexible for different scenarios.
Fixes #
```release-note
New configurations are added in the FluentBit Spec: command, livenessProbe, readinessProbe, initContainers, ports.
```

Make more fluent-bit configurations configurable via the FluentBit resource

---

apis/fluentbit/v1alpha2/fluentbit_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
apis/fluentd/v1alpha1/fluentd_types.go
apis/fluentd/v1alpha1/zz_generated.deepcopy.go
charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
charts/fluent-operator/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
controllers/fluentbit_controller.go
controllers/fluentd_controller.go
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/fluent-bit-service.go
pkg/operator/fluentd-service.go
pkg/operator/rbac.go

Signed-off-by: Kristian-ZH <k.zhelyazkov@sap.com>
The PR adds fluent-bit service that can be disabled with the configuration `DisableService`. It also adds an option to extend the RBAC configurations through the FB/Fluentd Spec config file.
Motivation:
The Service is needed in case you want to easily scrape metrics from the fluent-bit from Prometheus for example.
The RBAC extension is needed in case you deploy your custom output plugin (As the operator and the FB itself already support this option) and this custom plugin works with additional resources.
Fixes #
```release-note
The operator now deploys fluent-bit service which can be disabled with `DisableService` configuration in the FluentBit
```
```release-note
FluentBit and FluentD resources now support `rbacRules` configuration which …
```

Add fluent-bit service and option to extend the RBAC configurations

---

apis/fluentbit/v1alpha2/fluentbit_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR adds the functionality to add labels to to fluent-bit and fluent-operator.
I tested it with `helm template` a few times and it looks good. So at least no obvious helm errors However, I did not deploy it anywhere so far. Please test carefully before merging.
partially addresses: https://github.com/fluent/fluent-operator/issues/456
```release-note
With this updated version you can now add custom labels to fluent-bit and fluent-operator pods. For example refer to the values file.
```
```docs
```

feat: adding support for labels for fluent-operator and fluent-bit pods

---

cmd/fluent-watcher/fluentbit/main.go

Add an external plugin flag in the Fluent-Bit watcher which allows providing custom plugins to the FB binary.
Fixes #
```release-note
fluent-bit-watcher binary now supports `-e` flag which accepts an external plugin path
```

Add external plugin flag in the Fluent-Bit watcher

---

pkg/operator/daemonset.go

This PR will add annotations not only to fluent-bit pods, but also to the Daemon Set itself.
This is a slight detail I overlooked in my latest PR ( https://github.com/fluent/fluent-operator/pull/468 )
partially adresses https://github.com/fluent/fluent-operator/issues/456
```release-note
With this release you get the ability to add annotations to fluent-bit pods and the fluent-bit Dameon-Set generated.
```
```docs
```

feat: adding annotations to Dameon Set of fluent-bit

---

apis/fluentbit/v1alpha2/clusterinput_types_test.go
apis/fluentbit/v1alpha2/plugins/input/tail_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusterinputs.yaml
config/crd/bases/fluentbit.fluent.io_clusterinputs.yaml
docs/plugins/fluentbit/clusterinput/tail.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Implements an optional "dockerModeParser" parameter for FluentBit input tail
Fixes #
```release-note
Users can now specify an optional parser for parsing multiline logs with docker mode
```
```docs
Same usage as described in https://docs.fluentbit.io/manual/pipeline/inputs/tail#docker_mode
```

dockerModeParser parameter for ClusterInput tail

---

.github/workflows/build-fb-image.yaml
Makefile
charts/fluent-operator/values.yaml
cmd/fluent-watcher/fluentbit/Dockerfile
manifests/kubeedge/fluentbit-fluentbit-edge.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

This PR bumps fluent-bit to v2.0.6
This PR doesn't fix anything special, but sightly improves work with Grafana Loki output 
```release-note
Upgrade fluent-bit to v2.0.6
```
```docs
This PR upgrades fluent-bit to v2.0.6 what can introduce breaking changes in certain situations for some plugins (like Loki output plugin, for example). Consult with fluent-bit 2.0 release notes for details
```

Fluent-bit upgrade to v2.0.6

---

.github/dependabot.yml

There was a typo in the path to the fluent-bit watcher Dockerfile, causing Dependabot to ignore it. In addition, the update schedule was changed, to consume new versions of fluent-bit, etc. faster.
None
```release-note
None
```
```docs
```

dependabot: Update schedule and fix typo

---

docs/plugins/fluentd/common/buffer.md

Signed-off-by: Samantha Castille <54690345+samanthacastille@users.noreply.github.com>
Fixes a discrepancy between definitions of `flushThreadCount` between this file and online fluent documentation. According to the issue I submitted, online docs prevail.
Fixes #489 
```release-note
None
```
```docs
https://docs.fluentd.org/configuration/buffer-section#buffering-parameters
```

Update definition of flushThreadCount

---

cmd/fluent-watcher/fluentbit/main.go

Implements a timeout parameter in fluent-bit-watcher for killing fluent-bit in case it fails to terminate
In addition the commit also contains following changes:
- additional err/nil check for some actions,
- adds timestamps to fluent-bit-watcher logs as well as additional logs and some changed,
- changes deprecated imports: "github.com/go-kit/kit/log" to "github.com/go-kit/log" and "github.com/go-kit/kit/log/level" to "github.com/go-kit/log/level"
Please let me know if you spot any issues or something that would be worth improving. I've tested it at work with the default timeout of 30s and it seems to be working whenever the issue appears. For local testing "-flb-timeout 20ms" can be used to force kill fluent-bit before it manages to terminate. If needed I can post some logs.
Fixes #510 …

fluent-bit-watcher: timeout parameter, log timestamps, new/changed logs, additional nil/err checks

---

apis/fluentd/v1alpha1/plugins/output/loki.go
apis/fluentd/v1alpha1/plugins/output/types.go
apis/fluentd/v1alpha1/plugins/tls_types.go
apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-loki.cfg
apis/fluentd/v1alpha1/tests/tools.go
charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #522 Made CRD and operator conform to fluentd-loki-output-plugin documentation
```release-note
None
```
```docs
```

Fixes #522 CRD and operator conform to fluentd-loki-output-plugin documentation

---

apis/fluentbit/v1alpha2/clusterfilter_types_test.go
apis/fluentbit/v1alpha2/fluentbit_types.go
apis/fluentbit/v1alpha2/plugins/filter/kubernetes_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusterfilters.yaml
charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentbit.fluent.io_clusterfilters.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
controllers/collector_controller.go
docs/plugins/fluentbit/clusterfilter/kubernetes.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/daemonset.go

Signed-off-by: Jedrzej Kotkowski <jedrzejk143@gmail.com>
- Adds dnsPolicy option to FluentBit CRD
- Adds these options to FluentBit k8s filter plugin: dnsRetries, dnsWaitTime, useKubelet, kubeletPort, kubeletHost, kubeMetaCacheTTL, kubeTokenTTL
Fixes #524, #514
```release-note
Users can now specify dnsPolicy for FluentBit as well as more options for Kubernetes filter plugin
```
```docs
```

feature: add dnsPolicy to fluentbit, more options to kubernetes filter

---

charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
config/crd/bases/kustomization.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

I guess this was missed as a part of #484 - currently 'make manifests' does not generate the Collector CRD in manifests/setup because kustomization is missing it.
Also Fixes #513 - added Collector to the ClusterRole Helm template
```release-note
No
```
```docs
```

fix: added Collector CRD to kustomization & Helm ClusterRole template

---

pkg/operator/daemonset.go

Fixes #
```release-note
```
In the pr https://github.com/fluent/fluent-operator/pull/468, we added the label field, but not to the generated deployment file, and this pr is to fix that error.

adding support for labels for fluent-bit pods 

---

.github/workflows/main.yaml

Fixes #
```release-note
```
```docs
```

exclude docs from github action

---

pkg/operator/daemonset.go

Fixes #
```release-note
```
```docs
```

Fix the bug of adding label

---

apis/fluentbit/v1alpha2/clusteroutput_types.go
apis/fluentbit/v1alpha2/plugins/output/azure_blob_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
docs/fluentbit.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

PR creates an Azure Blob Output plugin, needed as part of the fluent-operator roadmap to add more output plugins.
Fixes #547
Let me know what I've (likely) missed/done wrong and happy to fix 👍🏻

Adding Azure Blob output plugin

---

apis/fluentbit/v1alpha2/clusterfilter_types.go
apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
apis/fluentbit/v1alpha2/clusteroutput_types.go
apis/fluentbit/v1alpha2/clusterparser_types.go
apis/fluentbit/v1alpha2/doc.go
apis/fluentd/v1alpha1/clusterfilter_types.go
apis/fluentd/v1alpha1/clusterfluentdconfig_types.go
apis/fluentd/v1alpha1/clusteroutput_types.go
apis/fluentd/v1alpha1/filter_types.go
apis/fluentd/v1alpha1/fluentd_types.go
apis/fluentd/v1alpha1/fluentdconfig_types.go
apis/fluentd/v1alpha1/output_types.go
cmd/fluent-manager/main.go
controllers/collector_controller.go
controllers/fluentbit_controller.go
controllers/fluentbitconfig_controller.go
controllers/fluentd_controller.go
controllers/fluentdconfig_controller.go
controllers/suite_test.go
pkg/filenotify/filenotify.go
pkg/filenotify/fsnotify.go
pkg/filenotify/poller.go
pkg/fluentd/router/pluginstore.go
pkg/operator/collector-statefulset.go
pkg/utils/utils.go

Signed-off-by: fengshunli <1171313930@qq.com>
Fixes #
```release-note
```
```docs
```

Fix Code format (including comment)

---

.github/workflows/main.yaml

Fixes #
```release-note
```
```docs
```

Update kubebuilder and kubectl

---

charts/fluent-operator/crds/fluentd.fluent.io_clusterfilters.yaml
charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/crds/fluentd.fluent.io_filters.yaml
charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusterfilters.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_filters.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentbit/common.md
docs/plugins/fluentd/output/es.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #590 
```release-note
None
```
```docs
```

Fixes #590 Update CRDs description / Documentation, conform to code

---

apis/fluentbit/v1alpha2/fluentbit_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
docs/fluentbit.md
pkg/operator/daemonset.go
pkg/operator/fluent-bit-service.go

This change allows a user to specify a metrics port as part of their `FluentBit` custom resource.  This is useful for those who need to use a port other than 2020.
Fixes #
```release-note
Added the optional `metricsPort` property in the `FluentBit` custom resource allowing users to specify a port.  Port 2020 will be used by default if this property is not set.
```
```docs
An example of a partial FluentBit resource with this new property might look like this:
kind: FluentBit
metadata:
name: fluent-bit
namespace: fluent
labels:
app.kubernetes.io/name: fluent-bit
spec:
image: kubesphere/fluent-bit:v2.0.9
metricsPort: 32020
```

feat: add ability to customize metrics port

---

charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Update the manifests that should have been updated with https://github.com/fluent/fluent-operator/pull/587 for the `metricsPort` addition.
Fixes #
```release-note
```
```docs
```

config: run "make manifests" to generate metricsPort

---

charts/fluent-operator/templates/fluentbit-clusterinput-systemd.yaml
charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml
charts/fluent-operator/values.yaml

Make default ClusterInputs optional and configurable as already done for ClusterFilter objects.
Fixes [#594](https://github.com/fluent/fluent-operator/issues/594)
```release-note
Make default ClusterInputs optional and configurable
```
```docs
```

Make default ClusterInputs optional and configurable

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
apis/generated/clientset/versioned/clientset.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
config/crd/bases/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
go.mod
go.sum
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR allows to enable the http Healthcheck that is already implemented in fluentbit and described here: https://docs.fluentbit.io/manual/administration/monitoring#health-check-for-fluent-bit . Since the functionality to add liveness probes already exists it would allow users to setup the liveness probes of fluentbit pods in a way that they query the integrated healthcheck.
Users of the fluent-operator could use this to increase the observability and reliability of their fluentbit instances. 
Therefore I believe that this PR is loosely related to #321 . In my eyes it is related in the sense that it allows to enable the healthcheck and theoretically also to expose the healtcheck which could be queried by external tools or setup as kubernetes livenessProbe. 
**I did not test this in …

feat: Enable fluentbit healthcheck

---

apis/fluentbit/v1alpha2/clusteroutput_types.go
apis/fluentbit/v1alpha2/plugins/output/cloudwatch_types.go
charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
docs/fluentbit.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Part of the fluent-operator goal of adding more output plugins. Needed to further support the goal of the project (managing fluentd/fluentbit configuration via YAML manifests)
No active issue for this
```release-note
None
```
```docs
```

Adding Cloudwatch for Fluentbit Output Plugin

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-kubernetes.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml

when fluentbit stdout output is enabled:
* `fluentbit.io/exclude` is added to fluentbit. the current check only added the annotation if another annotations was defined
* `k8sLoggingExclude` parameter is added to the kubernetes filter to activate usage of the `fluentbit.io/exclude` annotation
None

properly exclude fluentbit output when stdout output is enabled

---

apis/fluentd/v1alpha1/fluentd_types.go
charts/fluent-operator/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
docs/fluentd.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/sts.go

Adds the ability to configure volumes and volumeClaimTemplates for Fluentd pods
Fixes #
```release-note
Users are now able to defines volumes and volumeClaimTemplates
```
```docs
```

Fluentd add volumes & volumeClaimTemplates

---

cmd/fluent-watcher/fluentbit/Dockerfile

Fixes #
```release-note
```
```docs
```

Remove the deprecated -i flag for go build

---

charts/fluent-operator/values.yaml

Fixes #
```release-note
Disable the stdout output for fluent-bit by default because we don't want the entire cluster's log is output to each flluentbit pod's logs
```
```docs
```

disable stdout output by default in helm

---

controllers/fluentbit_controller.go

In our monitoring stack, we've been noticing that each reconciliation from the fluentbit controller results in three 409 errors. See image below:
I believe this change fixes that, though understand you might have different thoughts on implementation, so happy to hear them!
```release-note
None
```
```docs
```

create or patch rbac objects

---

apis/fluentd/v1alpha1/fluentd_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
docs/fluentd.md
go.mod
go.sum
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/pvc.go
pkg/operator/sts.go

Fixes SIGSEGV when setting Fluentd.spec.buffer.DisableBufferVolume to true/false without setting any other options.
**Renames DisableBufferVolume to disableBufferVolume to follow the camelCase pattern for field names. While this is technically a breaking change, the fact that this option was bugged and worked only under some specific conditions leads me to believe it shouldn't affect many (if anyone at all). Either way, if you think we should avoid such changes, I will revert it.**
This PR also includes some updates that were missed in previous PRs
Fixes #620 
```release-note
This PR renames Fluentd.spec.buffer.DisableBufferVolume to disableBufferVolume, setups might have to be adjusted.
```
```docs
```

fix segfault with DisableBuferVollume, rename to disableBufferVolume

---

apis/fluentbit/v1alpha2/collector_types.go
apis/fluentbit/v1alpha2/fluentbit_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
apis/fluentd/v1alpha1/fluentd_types.go
apis/fluentd/v1alpha1/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_collectors.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbits.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentbit.fluent.io_collectors.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
controllers/collector_controller.go
controllers/fluentbit_controller.go
controllers/fluentd_controller.go
docs/fluentbit.md
docs/fluentd.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/rbac.go

Currently, if you wanted to use Workload Identity - you'd have to manually annotate the fluentbit/fluentd service account, and then restart the pods for authentication to occur. (Sometimes it worked without authentication). This PR allows for annotations to be added to the service account and a restart of fluentbit/fluentd to occur.
Fixes #562 
```release-note
None (or not really, more an optional field than any action required)
```
```docs
See PR for docs.md
```

Enable annotations for service account in fluentbit/fluentd

---

charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
manifests/setup/fluent-operator-clusterRole.yaml

Fix the helm template permissions for clusterrole and clusterrole bindings
- Added list, get, watch, patch to the clusterrole resource
- Added list, get, watch, patch to the clusterrolebinding resource
Fixes #646 
```release-note
None
```
```docs
```

fix: Fix the permissions in the cluster roles and bindings in helm

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
apis/fluentbit/v1alpha2/plugins/secret_types.go
controllers/fluentbitconfig_controller.go

For namespaced FluentBit configs, search for secrets in the same namespace as the configs.
Fixes #653 
```release-note
```
```docs
```

Namespace level secret loader for namespaced FluentBit configs

---

pkg/operator/rbac.go

THIS PR Change the naming of RBAC Object created by the operator.
Today RBAC Object does not support multiple instances of FluentBit making secondary agent unable to query k8s apis
None, except multiple clusterrolebinding / rolebinding creation during reconciliation

Make RBAC comptaible with multiple instances

---

.github/workflows/build-fb-image.yaml
charts/fluent-operator/templates/fluentbit-fluentbit-edge.yaml
charts/fluent-operator/templates/fluentbit-input-node-exporter-metrics-edge.yaml
charts/fluent-operator/templates/fluentbit-input-prometheus-scrape-metrics-edge.yaml
charts/fluent-operator/templates/fluentbit-output-prometheus-remote-write-edge.yaml
charts/fluent-operator/templates/fluentbitconfig-fluentbitconfig-edge.yaml
charts/fluent-operator/values.yaml

Fixes #
```release-note
```
```docs
```

Add the YAML file for edge nodes to the Helm file

---

apis/fluentd/v1alpha1/fluentd_types.go
apis/fluentd/v1alpha1/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
docs/fluentd.md
pkg/operator/sts.go

Hi, I would like to add the ability to set envVars to Fluentd.
```release-note
- Environment variables can be now passed into Fluentd Pod.
```
```docs
```

Add EnvVars support to FluentD

---

apis/fluentd/v1alpha1/fluentd_types.go
apis/fluentd/v1alpha1/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
docs/fluentd.md
pkg/operator/sts.go

Hi, I would like to add the ability to set annotations to Fluentd.
```release-note
- Annotations can be now passed into Fluentd Pod.
```
```docs
```

Add Pod Annotations support to FluentD

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

Added support for tolerations, nodeSelector, priorityClassName and podSecurityContext to fluent-operator deployment and fluentbit daemonset
Fixes https://github.com/fluent/helm-charts/issues/314 
Fixes #695 
```release-note
Added support for tolerations, nodeSelector, priorityClassName and podSecurityContext to fluent-operator deployment and fluentbit daemonset
```
```docs
```

fluent operator & fluentbit: Added tolerations, nodeSelector + more

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

Added possibility to set envVars for the fluent-bit template.
Useful for when you would want to set and use a environment variable in your filters and you don't want to configure your own `FluentBit` and instead use the templated one from the helm chart.
```release-note
Added possibility to set envVars for the fluent-bit template.
```
```docs
```

envVars support in fluentbit helm template

---

apis/fluentbit/v1alpha2/plugins/output/open_telemetry_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
docs/fluentbit.md
docs/plugins/fluentbit/filter/recordmodifier.md
docs/plugins/fluentbit/output/influxdb.md
docs/plugins/fluentbit/output/open_telemetry.md
docs/plugins/fluentbit/secret.md
go.mod
go.sum
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Adds a field for each telemetry type in the opentelemetry clusteroutput-plugin so it matches the fluent bit opentelemetry output, as described in the [docs](https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry)
Fixes #707
```release-note
```
```docs
```

Add uri field for each telemetry type in opentelemetry plugin, remove old uri field

---

cmd/fluent-watcher/fluentd/Dockerfile.amd64
cmd/fluent-watcher/fluentd/Dockerfile.arm64
cmd/fluent-watcher/fluentd/Dockerfile.arm64.quick

Fixes #
```release-note
```
```docs
```

remove the deprecated -i flag in go build

---

charts/fluent-operator/values.yaml

The link to the GitHub path containing all outputs plugins has changed from `clusteroutput` to `output `
Update link in Helm values file to correct link.
N/A
```release-note
None
```
```docs
```

Fix(docs): Update cluster outputs docs link

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

Allows to configure fluentbit pods affinity,  which is useful for adding a rule to not to schedule a pod on a node based on a label.
values.yaml example:
```
fluentbit:
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: node-role.kubernetes.io/edge
operator: DoesNotExist
- key: fluentbit.cluster.local/schedulable
operator: NotIn
values:
- "false"
```
```release-note
None
```

Add fluentbit.affinity configuration

---

apis/fluentd/v1alpha1/plugins/filter/types.go

This PR fixes an issue with pointers not being dereferenced in Fluentd "parser" filter plugin
Fixes #741 
```release-note
None
```
```docs
```

fix: dereference pointers in parser filter plugin for fluentd

---

charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

Fixes #
```release-note
```
```docs
```

add some fluentbit helm opts

---

apis/fluentbit/v1alpha2/plugins/output/loki_types.go
apis/fluentbit/v1alpha2/plugins/output/zz_generated.deepcopy.go
apis/generated/clientset/versioned/fake/register.go
apis/generated/clientset/versioned/scheme/register.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
go.mod
go.sum
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR aligns the fluent-operator CRDs and Operator with the fluentbit loki output [plugin](https://docs.fluentbit.io/manual/pipeline/outputs/loki) by adding the properties `labelMapPath`, `removeKeys`, `dropSingleKey` and `tenantIDKey`.
Fixes #737 
```release-note
```
```docs
```

Align CRDs and Operator with the fluentbit loki output 

---

apis/fluentbit/v1alpha2/plugins/custom/custom_types.go
apis/fluentbit/v1alpha2/plugins/output/loki_types.go
apis/fluentd/v1alpha1/plugins/common/buffer_types.go
apis/fluentd/v1alpha1/plugins/input/tail.go
apis/generated/clientset/versioned/fake/register.go
apis/generated/clientset/versioned/scheme/register.go
docs/plugins/fluentbit/custom/custom.md
docs/plugins/fluentbit/output/loki.md

Adds 2 missing parameters to Fluentd output buffer section + make fmt & make docs-update
Fixes #752
```release-note
None
```
```docs
```

add missing fluentd buffer options

---

apis/fluentbit/v1alpha2/clusteroutput_types.go
apis/fluentbit/v1alpha2/plugins/output/kinesis_types.go
apis/fluentbit/v1alpha2/plugins/output/kinesis_types_test.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
cmd/doc-gen/main.go
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/fluentd.md
docs/plugins/fluentbit/output/kinesis.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

add another output plugin support for operator with additional minor typo fix
Fixes #
```release-note
add AWS Kinesis Data Streams output plugin for Fluent Bit
```
```docs
```

feat: add AWS Kinesis Data Streams output plugin for Fluent Bit

---

apis/fluentd/v1alpha1/fluentd_types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
controllers/fluentdconfig_controller.go
docs/fluentd.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

allow customers to configure global log_level setting for fluentd
related fluentd doc for reference: https://docs.fluentd.org/deployment/logging
Fixes #761
```release-note
add global log_level support for fluentd
```
```docs
```

feat: add global log_level support for fluentd

---

apis/fluentbit/v1alpha2/fluentbit_types.go
apis/fluentd/v1alpha1/fluentd_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbits.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/daemonset.go
pkg/operator/sts.go

allow customers to specify custom scheduler for fluentbit and fluentd pods
Fixes #758
```release-note
add scheduler support for fluentbit & fluentd
```
```docs
```

feat: add scheduler support for fluentbit & fluentd

---

apis/fluentbit/v1alpha2/collector_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_collectors.yaml
config/crd/bases/fluentbit.fluent.io_collectors.yaml
controllers/collector_controller.go
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/collector-service.go
pkg/operator/collector-statefulset.go

allow customers to specify custom scheduler for fluentbit collector as requested from [this comment](https://github.com/fluent/fluent-operator/pull/771#issuecomment-1574624390). along with minor typo fix.
Fixes #
```release-note
allow customers to specify custom scheduler for fluentbit collector
```
```docs
```

feat: add scheduler support for fluentbit collector

---

charts/fluent-operator/templates/fluentbit-clusterinput-systemd.yaml
charts/fluent-operator/values.yaml

Introducing stripUnderscores in fluent-operator helm chart to strip the underscore prefix coming out from the Systemd input. By default, it is set as "off"
Fixes #774 
```release-note
```
```docs
```

Introduce stripUnderscores in fluent-operator helm values for fluentbit Input Systemd

---

apis/fluentd/v1alpha1/plugins/common/buffer_types.go
apis/fluentd/v1alpha1/plugins/common/common_types.go
apis/fluentd/v1alpha1/plugins/common/parse_types.go
apis/fluentd/v1alpha1/tests/expected/duplicate-removal-cr-specs.cfg
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusterfilters.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_filters.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_fluentds.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusterfilters.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_filters.yaml
config/crd/bases/fluentd.fluent.io_fluentds.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

It changes the TimeFormat config value from `time_type` to `time_format` as it should be.
Fixes #778
Fixes #781 
```release-note
Fix: Correct fluentd prase TimeFormat config key
Fix: Correct Kubebuilder validation for TimeType from *string to string
```
```docs
```

Fix: Correct fluentd prase TimeFormat config key

---

controllers/collector_controller.go
controllers/fluent_controller_finalizer.go
controllers/fluentbit_controller.go
controllers/fluentd_controller.go
pkg/operator/rbac.go

~resources like sa, svc and sts haven't been generated before calling `Delete()` which leads to the remaining finalizer for collector.~
resource deletion and adoption cleanup and fix for 3 controllers
Fixes #
```release-note
None
```
```docs
```

fix: resource deletion and adoption for 3 controllers

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml

Rename field podSecurityContext to securityContext in Fluent Operator Deployment. As `podSecurityContext` is invalid field. The correct field is securityContext
Fixes #789 
```release-note
```
```docs
```

Rename field podSecurityContext to securityContext in Fluent Operator Deployment

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

Introduce podSecurityContext in fluent operator helm chart so that it can be passed to fluentbit CR.
Fixes #787 
```release-note
```
```docs
```

Add podSecurityContext for fluentbit in fluent operator helm chart

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/values.yaml

Add  fluent operator security context at container level in fluent Operator helm chart.
Fixes #791 
```release-note
```
```docs
```

Add fluent operator security context at container level

---

pkg/operator/pvc.go

Fixes #798 
```release-note
None
```
```docs
```

Fixes #798 storageClassName field not taken into account

---

apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
apis/fluentd/v1alpha1/plugins/output/datadog.go
apis/fluentd/v1alpha1/plugins/output/types.go
apis/fluentd/v1alpha1/plugins/params/const.go
apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-datadog.cfg
apis/fluentd/v1alpha1/tests/helper_test.go
apis/fluentd/v1alpha1/tests/tools.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbits.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
cmd/fluent-watcher/fluentd/Dockerfile.amd64
cmd/fluent-watcher/fluentd/Dockerfile.arm64
cmd/fluent-watcher/fluentd/Dockerfile.arm64.base
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/fluentbit.md
docs/fluentd.md
docs/plugins/fluentd/common/common.md
docs/plugins/fluentd/output/datadog.md
docs/plugins/fluentd/output/types.md
go.mod
go.sum
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR adds support for the Fluentd [datadog](https://github.com/DataDog/fluent-plugin-datadog) output plugin.
Fixes #797 
```release-note
None
```

Adds the fluentd output plugin for Datadog

---

cmd/fluent-watcher/fluentd/base/Dockerfile

Setting fluent-plugin-opensearch to v1.1.0. Version v1.1.1 is broken.
Fixes #814 
```release-note
```
```docs
```

Update fluentd base Dockerfile

---

charts/fluent-operator/templates/_helpers.tpl

Fixes #
```release-note
```
```docs
```

Update the _helpers.tpl file

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/values.yaml

Not having resources specified for init containers prevents deployments in environments where resource definitions are mandated by policy.
Fixes #816 
```release-note
None
```
None.

Specify init container resources for fluent-operator deployment

---

cmd/upgrade/upgrade.sh

During the process of upgrading the fluentbit-operator, this script helps the user to convert the original configuration to the new one and to uninstall the `fluentbit-operator`.
Fixes #
```release-note
```
```docs
```

Upgrade fluentbit-operator to fluent-operator

---

apis/fluentd/v1alpha1/plugins/common/buffer_types.go
apis/fluentd/v1alpha1/tests/expected/duplicate-removal-cr-specs.cfg

Fixes #
```release-note
none
```
```docs
```

fix: incorrect field names in fluentd buffer plugin

---

apis/fluentbit/v1alpha2/fluentbit_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
docs/fluentbit.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/daemonset.go

Fixes #833 
```release-note
None
```
```docs
```

mountPropagation option for internal mounts (#833)

---

apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
apis/fluentd/v1alpha1/plugins/output/s3.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentd/output/s3.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

For the s3 output plugin of Fluentd, parameters are added to be compatible with minio
Fixes #849
```release-note
The following fields were added to the fluentd S3 output plugin
- 's3Endpoint': The endpoint URL (like "http://localhost:9000/")
- 'forcePathStyle': This prevents AWS SDK from breaking endpoint URL
- 'timeSliceFormat': This timestamp is added to each file name
```
```docs
- [Usage]: [Send Apache Logs to Minio](https://docs.fluentd.org/how-to-guides/apache-to-minio)
- [Other doc]: [S3](https://docs.fluentd.org/output/s3)
```

[Fix]Fluentd's s3 output plugin is compatible with minio

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

add option to setup hostNetwork for daemonset
#862 
Fixes #
None
```docs
Add option to setup hostNetwork propertie for fluent-bit DaemonSet for fluentbit-operator helm chart
```

add option to configure hostNetwork daemonset propertie

---

charts/fluent-operator/templates/fluentbit-output-elasticsearch.yaml
charts/fluent-operator/values.yaml

Newer ElasticSearch versions (more than 7) needs `suppressTypeName: On` for work

Added SuppressTypeName option to helm, as newer ES needs it for bulk operation

---

charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml

This PR allows arbitrary features from the FluentD CRD to be used as they are developed
Fixes #888
```release-note
None
```

PR for #888

---

charts/fluent-operator/templates/fluentbit-output-loki.yaml
charts/fluent-operator/values.yaml

See #864 
Fixes #864
```release-note
No changes required for existing installations/users. Users wishing to use the extra functionality should add a loki section to their values.yaml as documented therein
```
```docs
```

#864 Helm chart generation of ClusterOutput for loki

---

charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml

Fixes #879 
```release-note
None
```
We already have support for fluentd. It was just not added in values.yaml.
In FluentdSpec:
In MakeFluentdDaemonSet:

Add ImagePullSecret for fluentd

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

We're deploying the fluent-operator, and corresponding FluentBit resource, on an AWS EKS cluster. As we are using IAM Roles for Service Accounts, we need the ability to add the below annotation to the service account to provide the fluent-bit Pods with access to push to our log sink: 
```
metadata:
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/fluent-bit-role
```
Without this, we see the follow error messages in the fluent-bit Pods: 
```
[2023/08/25 12:41:41] [error] [aws_credentials] STS assume role request failed
[2023/08/25 12:41:41] [ warn] [aws_credentials] No cached credentials are available and a credential refresh is already in progress. The current co-routine will retry.
```
With the changes in this PR, the service account is correctly annotated to …

feat: added serviceAccountAnnotations to FluentBit resource

---

apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/fluentbit.md
docs/plugins/fluentbit/output/elasticsearch.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Add compress in fluentbit output es
Fixes #511 
```release-note
```
```docs
```

add compress in fluentbit output es

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml

Unfortunately, the fluentd section does not currently support setting the priorityClassName field, which may be required in some environments. To solve this problem, I made this small change.
Fixes #
```release-note
None
```
```docs
```

feat: added Helm priorityClassName mapping to fluentd

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentd-clusterfluentdconfig.yaml

To be able to set an empty array for watchedNamespaces, we need to change the way properties are added. Currently, if we set an empty array as a property, we get the following error message:  `ClusterFluentdConfig.fluentd.fluent.io "fluentd-config" is invalid: spec.watchedNamespaces: Invalid value: "null": spec.watchedNamespaces in body must be of type array: "null"`. The reason for this error message is that `[]` does not count as a value with an index, so the CR key is set to `null`, which is not a valid value.
See description above.
```release-note
None
```
```docs
```

fix: fluentd watchedNamespaces Helm mapping

---

pkg/operator/collector-statefulset.go

Pods created by the statefulset of a collector, doesn't expose the ports defined. Only, the service expose the ports.
This PR add those ports to the definition of the statefulset.
Fixes #916
```release-note
None
```
```docs
```

Expose ports on collector statefulset

---

CHANGELOG.md
README.md
RELEASE.md
charts/fluent-operator/Chart.yaml
charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
charts/fluent-operator/charts/fluentd-crds/Chart.yaml

Fixes #
```release-note
release 2.5.0
```
```docs
```

release 2.5.0

---

apis/fluentbit/v1alpha2/fluentbit_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbits.yaml
config/crd/bases/fluentbit.fluent.io_fluentbits.yaml
config/samples/fluentbit_v1alpha2_fluentbit.yaml
docs/fluentbit.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml
pkg/operator/daemonset.go

Currenly, fluentbit daemonset mounts three hostPath volumes. HostPath is forbidden in some k8s environments. This PR adds a flag `disableLogVolumes` to disable these mounts. 
Fixes #907

add fluentbit daemonset hostPath toggle

---

charts/fluent-operator/templates/fluentd-output-opensearch.yaml

Signed-off-by stefan.hynek@uni-goettingen.de
add spec.outputs.opensearch.scheme value to allow for https connections
Fixes #579
```release-note
None
```
```docs
```

fix(fluentd-output-opensearch): add spec.outputs.opensearch.scheme value

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml
charts/fluent-operator/templates/fluentbitconfig-fluentbitconfig-edge.yaml

Add parserSelector for helm chart ClusterFluentBitConfig templates, allowing this config to use custom Parser resources
e.g.
```
{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
kind: ClusterFluentBitConfig
metadata:
name: fluent-bit-config
labels:
app.kubernetes.io/name: fluent-bit
spec:
service:
parsersFile: parsers.conf
httpServer: true
{{- if .Values.fluentbit.service.storage }}
storage:
{{ toYaml .Values.fluentbit.service.storage | indent 6 }}
{{- end }}
inputSelector:
matchLabels:
fluentbit.fluent.io/enabled: "true"
filterSelector:
matchLabels:
fluentbit.fluent.io/enabled: "true"
outputSelector:
matchLabels:
fluentbit.fluent.io/enabled: "true"
{{- end }}
{{- end }}
```
Fixes #955
```release-note
None
```
```docs
```

fix: add parserSelector to clusterFluentBitConfig chart templates

---

apis/fluentd/v1alpha1/plugins/filter/types.go
apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-filter-recordTransformer.cfg
apis/fluentd/v1alpha1/tests/helper_test.go
apis/fluentd/v1alpha1/tests/tools.go

Fixes #959
```release-note
None
```
```docs
```

fix: fix fd record transformer parameters

---

apis/fluentd/v1alpha1/plugins/input/types.go

Fixes #965
```release-note
None
```
```docs
```

fix: fix fluentd in_http plugin keepalive_timeout option

---

.github/workflows/lint-test.yaml

Update `.github/workflows/lint-test.yaml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=changed::true"
```
**TO-BE**
```yaml
echo "changed=true" >> $GITHUB_OUTPUT
```
Fixes #969 
```release-note
None
```
```docs
```

chore: Replace deprecated command with environment file

---

cmd/fluent-watcher/fluentd/Dockerfile.amd64
cmd/fluent-watcher/fluentd/Dockerfile.arm64
cmd/fluent-watcher/fluentd/Dockerfile.arm64.base

This PR installs the `fluent-plugin-prometheus` plugin.  This plugin is required for work related to #813 
Complements #725 
None.

Adds the fluent-plugin-prometheus plugin to fluentd.

---

conf/parsers.conf

Adds Time_Keep parameter to default cri parser so time tag exists at output; matching a change to the parsers.conf in the [fluent-bit repo](https://github.com/fluent/fluent-bit/commit/6315a8a07ab1dd4d40de89002b697f20232f204e)
Fixes #957
```release-note
```
```docs
```

default cri parser should contain Time_Keep On, otherwise no time tag exists at output

---

.github/workflows/lint-test.yaml

Fix lint test error  https://github.com/fluent/fluent-operator/actions/runs/6734151112/job/18304382921?pr=967
Fixes #
```release-note
Fix "ERROR: Unable to validate cosign version: 'v2.0.0'"
```
```docs
```

Upgrade chart-testing-action to v2.6.0

---

.github/workflows/lint-test.yaml
charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml

This PR adds the ability to pass environment variables to `fluentd` when using the `fluent-operator` Helm chart.
Fixes #942.
```release-note
none
```
```docs
```

feat(fluentd): allow passing env vars using the chart

---

apis/fluentd/v1alpha1/helper.go

Currently, there is no determined order of clusterinputs, clusterfilters, and clusteroutputs. If a user wants to use fluentd rewrite_tag_filter, then unordered clusterfilters may affect the final results of log entries.
fluent-bit has similar feature.
Fixes #
```release-note
Fluentd  clusterinputs, clusterfilters, and clusteroutputs will be sorted by metadata.name
```
```docs
```

feat: sort custom resources by metadata.name

---

apis/fluentd/v1alpha1/plugins/output/es.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentd/output/es.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #418 
```release-note
None
```
```docs
```

fix: Add SSL/TLS settings feature for fluentd output Elasticsearch #418

---

apis/fluentd/v1alpha1/helper.go
apis/fluentd/v1alpha1/plugins/output/copy.go
apis/fluentd/v1alpha1/plugins/output/types.go
apis/fluentd/v1alpha1/plugins/params/const.go
apis/fluentd/v1alpha1/plugins/params/model.go
apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-stdout-and-loki.cfg
apis/fluentd/v1alpha1/tests/expected/fluentd-mixed-cfgs-output-copy-1.cfg
apis/fluentd/v1alpha1/tests/expected/fluentd-mixed-cfgs-output-copy-2.cfg
apis/fluentd/v1alpha1/tests/expected/fluentd-mixed-cfgs-output-copy-3.cfg
apis/fluentd/v1alpha1/tests/helper_test.go
apis/fluentd/v1alpha1/tests/tools.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
controllers/fluentdconfig_controller.go
docs/plugins/fluentd/output/copy.md
docs/plugins/fluentd/output/types.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Feat #1017 
```release-note
None
```
```docs
```

feat: Add copy output plugin for fluentd #1017

---

charts/fluent-operator/templates/fluentbit-output-loki.yaml

Signed-off-by: Ilya Semichastnov <isemichastnov@gmail.com>
Fixed the .spec.loki.tls map rendering in FluentBit loki ClusterOutput
Fixes #
```release-note
Fixed the .spec.loki.tls map rendering in FluentBit loki ClusterOutput
```
```docs
```

Fixed the .spec.loki.tls map rendering in FluentBit loki ClusterOutput

---

charts/fluent-operator/templates/fluentbit-output-stackdriver.yaml
charts/fluent-operator/values.yaml
docs/plugins/fluentbit/index.md

Add the stackdriver fluentbit output for the helm chart for users that deploys to GKE clusters.
Fixes #1038
```release-note
Added stackdriver fluentbit output for the helm chart. 
```
```docs
- [Usage]: https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentbit/output/stackdriver.md
- [Other doc]: https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver
```

Add stackdriver output to the Helm Chart

---

apis/fluentd/v1alpha1/plugins/params/model.go

This fixes a small issue regarding custom plugins by adding `PluginStore.Content` to the hash generation. Otherwise every custom plugin would have the same hash and only one would be added to the final config.
Since `PluginStore.Content` is empty for all plugins except custom ones it is safe to just set it when calculating the hash.
No.
n.a.

fix(fluentd): Use custom plugin content for hash generation

---

charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml
charts/fluent-operator/values.yaml

Fixes https://github.com/fluent/fluent-operator/issues/1062
```release-note
allow configuration of logLevel in ClusterFluentBitConfig helm template
```
```docs
```

feat(1062): Configure logLevel in ClusterFluentBitConfig

---

charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml
charts/fluent-operator/values.yaml

Add clusterinput tail resource to support setting **bufferMaxSize**
Fixes #1043 
```release-note
```
```docs
```

Add clusterinput tail resource to support setting bufferMaxSize

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
apis/fluentbit/v1alpha2/clusterfluentbitconfig_types_test.go
cmd/fluent-watcher/fluentbit/main.go
go.mod
go.sum

**Note:** I recognize that I haven't proposed this change per-se and that it's not necessarily necessary to do this rework in order to implement hot-reload. I'm happy to change things around and I don't want to come across as "here's a rework, plz merge" 😅 . This is more of a discussion-base for now.
This reworks the fluent-bit-watcher to be "single-child-process" only. Since we can now use hot-reload, we don't need to account for potential fluent-bit restarts "under the hood" and can instead rely on a single process to live "forever". Whenever that one fluent-bit process exits, the watcher should exit as well and Kubernetes' `CrashLoopBackoff` take care of the rest.
That fundamental change in assumption allows us to vastly simplify the lifecycle in the watcher, which this does. It gets …

Rework fluent-bit-watcher and make use of the hot-reload mechanism

---

apis/fluentbit/v1alpha2/plugins/filter/multiline_types.go
apis/fluentbit/v1alpha2/plugins/filter/rewritetag_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfilters.yaml

Adds an ability to specify emitter storage type (fs or memory) and emitter buffer size.
Fixes https://github.com/fluent/fluent-bit/issues/4940
None
filters:
- rewriteTag:
emitterName: rewrite_em
emitterStorageType: filesystem
emitterMemBufLimit: 128MB
- multiline:
emitterName: multiline_em
emitterStorageType: filesystem
emitterMemBufLimit: 128MB
keyContent: log
parser: python

feat: Emitter storage_type and mem_buf_limit config

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/values.yaml

This would allow users to provide extra arguments like --watch-namespaces
Fixes #1073
```release-note
Helm Chart: Add operator.extraArgs in chart values to add extra args to the fluent-operator container.
```
```docs
```

feat(chart): Add operator.extraArgs to add extra args to the fluent-operator container

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types_test.go
apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/elasticsearch.md

Add WriteOperation option to output plugin ElasticSearch. This option is supported by the fluentbit perse as seen in https://github.com/fluent/fluent-bit/blob/9d9ac68a2b45a4cedeafbf7c5aba513f494eced6/plugins/out_es/es_conf.c#L304 . 
Fixes #
User now can use option `writeOption` to adjust their ES bulk api call.
```docs
```

fluentbit/output/elasticsearch: Add writeOperation option

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

No
```release-note
feat(disableLogVolumes): expose disableLogVolumes in helm chart
```

feat(disableLogVolumes): expose disableLogVolumes in helm chart

---

apis/fluentbit/v1alpha2/plugins/filter/lua_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_filters.yaml

Adds support for "code:" inline block in LUA namespace-wide filter.
See: https://docs.fluentbit.io/manual/pipeline/filters/lua
"code | Inline LUA code instead of loading from a path via script."
```release-note
None
```
```docs
Usage:
kind: Filter
metadata:
labels:
fluentbit.fluent.io/enabled: "true"
name: test
spec:
match: "*"
filters:
- lua:
call: converter
protectedMode: true 
code: |
function converter(tag, timestamp, record)
return 0, 0, 0
end
```

LUA filter inline code support

---

apis/fluentbit/v1alpha2/plugins/input/syslog.go

It fixes a bug in the syslog input plugin, where some of the fields were incorrectly assigned to the kvs.
Fixes #1083
```release-note
None
```
```docs
```

fix: incorrect fields in syslog input plugin parameters

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
apis/fluentbit/v1alpha2/fluentbitconfig_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbitconfigs.yaml
controllers/fluentbitconfig_controller.go

Adds parameters to fine-tune namespaced tag re_emitter.
Same as: https://github.com/fluent/fluent-operator/pull/1069 but for namespaced filters.
Fixes issues with emitter pause on overflow.
```release-note
None
```
```docs
Usage:
kind: FluentBitConfig
metadata:
name: fluent-bit-config
labels:
app.kubernetes.io/name: fluent-bit
spec:
filterSelector:
matchLabels:
fluentbit.fluent.io/enabled: "true"
outputSelector:
matchLabels:
fluentbit.fluent.io/enabled: "true"
parserSelector:
matchLabels:
fluentbit.fluent.io/enabled: "true"
service:
emitterName: test
emitterStorageType: filesystem
emitterMemBufLimit: 16MB
```
generates config like this:
```
[Filter]
Name    rewrite_tag
Match    kube.*
Rule    $kubernetes['namespace_name'] ^(test)$ …
```

namespaced tag re_emitter parameters support

---

.github/workflows/build-fb-image.yaml
.github/workflows/build-fd-image.yaml
.github/workflows/build-op-image.yaml
.github/workflows/clone-docker-image-action.yaml
.github/workflows/scan-docker-image-action.yaml

Push images to multiple registries; images: fluentbit, fluent-operator
Current system is pushing images to only single registry: Docker Hub;
We want to push images to other registries too; to solve this we are pushing every image to GitHub Container Registry and then we only release image to docker hub if they are changes towards master or tags.
This is a new PR for the requested changes in https://github.com/fluent/fluent-operator/pull/1071
Fixes #1068 
```release-note
```
```docs
We are currently defining default image names and tags
kubesphere/fluent-bit:v2.2.2
kubesphere/fluent-bit:v2.2.2-debug
This commit would be changed to tag based versioning; if a new git tag is released, new tag would be used for images.
Images will be pushing to …
```

push image to multiple registry

---

.github/workflows/build-fb-image.yaml
.github/workflows/build-fd-image.yaml
.github/workflows/build-op-image.yaml
.github/workflows/clone-docker-image-action.yaml
.github/workflows/scan-docker-image-action.yaml

This PR solves the problem of not pushing the latest tag to docker hub. Pushing this tag is mandatory as discussed in the PR https://github.com/fluent/fluent-operator/pull/1079
Fixes #1068 
GitHub action jobs - than ran on my personal credentials with tag [v23.1.1](https://github.com/sarathchandra24/fluent-operator/tree/v23.1.1) - this is just a temporary tag to check the creation of images.
[Fluentd Job](https://github.com/sarathchandra24/fluent-operator/actions/runs/8217761452)
[Fluent-Bit Job](https://github.com/sarathchandra24/fluent-operator/actions/runs/8220329710) - In Progress
[Fluent Operator Job](https://github.com/sarathchandra24/fluent-operator/actions/runs/8220329713)
Verification of images pushed to docker hub:
[fluent-operator](hub.docker.com/repository/docker/sarathchandra2 …

Fix: attach latest tag to images - DockerHub synchronize with GHCR

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml

- when hostNetwork is true and dnsPolicy is not filled in, default to `ClusterFirstWithHostNet`
It changes the default behavior when hostNetwork is true and dnsPolicy is not filled in to use `ClusterFirstWithHostNet`. 
[Pod's DNS Policy](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy)
Fixes #
```release-note
```
```docs
```

HostNetwork DNS Policy

---

Makefile
cmd/fluent-watcher/fluentd/Dockerfile.arm64.quick

Passing build args to docker image in pipelines to be able to run tagged builds.
Fixes #1094 
```release-note
```
```docs
```

fix build args fluentd image

---

cmd/fluent-watcher/fluentd/main.go

Fixes #1090 
```release-note
Fixes docker run path for fluentd
```
> docker run kubesphere/fluentd:v1.15.3-arm64  
is running the following
This changes fixes the path issue for fluentd
```docs
```

Fix 1090: Path issues

---

apis/fluentd/v1alpha1/tests/expected/fluentd-cluster-cfg-output-loki.cfg
apis/fluentd/v1alpha1/tests/expected/fluentd-mixed-cfgs-output-copy-1.cfg
apis/fluentd/v1alpha1/tests/tools.go

This PR enforce the tests for Fluentd Loki plugin
```release-note
```
```docs
```

feat: enforce Fluentd tests

---

charts/fluent-operator/templates/fluentbit-output-elasticsearch.yaml

It passes variables from values.yaml to Elasticsearch ClusterOutput. traceError and writeOperation were omitted.
Fixes #
None

Passing variables to es output config is fixed

---

cmd/doc-gen/main.go
docs/fluentbit.md
docs/plugins/fluentbit/filter/lua.md
docs/plugins/fluentbit/filter/multiline.md
docs/plugins/fluentbit/filter/rewritetag.md
docs/plugins/fluentbit/multilineparser/multilineparser.md

improve 
```
go run cmd/doc-gen/main.go
```
Fixes #1120 
None
```release-note
auto gen plugins documentation directory
```

auto gen plugins documentation directory

---

apis/fluentbit/v1alpha2/plugins/output/s3_types.go
apis/fluentbit/v1alpha2/plugins/output/s3_types_test.go

This adds support for the AWS credential `profile` field for the S3 Fluent Bit S3 ouput.  See [here](https://docs.fluentbit.io/manual/pipeline/outputs/s3).
Fixes #1126
```release-note
The `Profile` field for the `S3` output is added, which translates to the `profile` field for the Fluent bit S3 output.
```

Add Profile field for Fluent bit S3 output

---

charts/fluent-operator/templates/fluentbit-output-elasticsearch.yaml
charts/fluent-operator/values.yaml

helm template output es support logstashPrefixKey
Fixes  #1118 
None
- [Usage]: 
```docs
output:
es:
enable: true
host: 10.8.xx.xx
port: 9200
logstashPrefixKey: ks-logstash-log
buffer:
enable: false
type: file
path: /buffers/es
```

helm template fluentbit output es support logstashPrefixKey

---

apis/fluentbit/v1alpha2/clustermultilineparser_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/s3.md
go.mod
go.sum
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1131 #1132 
None
```release-note
MultilineParserSpec achieve an effect similar to embedding by using anonymous structs
add MultilineParser resource role in helm chart
```

MultilineParser achieve an effect similar to embedding by using anonymous structs

---

apis/fluentbit/v1alpha2/plugins/filter/lua_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfilters.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_filters.yaml
config/crd/bases/fluentbit.fluent.io_clusterfilters.yaml
config/crd/bases/fluentbit.fluent.io_filters.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1128 
None
```release-note
make lua scripts `code` and `script` optional
```
```

make lua scripts `code` and `script` optional

---

apis/fluentbit/v1alpha2/plugins/filter/lua_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfilters.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_filters.yaml
charts/fluent-operator/templates/fluentbit-clusterfilter-multiline.yaml
charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml
charts/fluent-operator/templates/fluentbit-multilineParser-javaMultiline.yaml
charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentbit.fluent.io_clusterfilters.yaml
config/crd/bases/fluentbit.fluent.io_filters.yaml
config/samples/fluentbit_v1alpha2_clustermultilineparser.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1137 
None
```release-note
Helm multiline passer template, support filter go python java multiline log
```
```docs
set helm values.yaml
parsers:
javaMultiline:
enable: true
filter:
multiline:
enable: false
keyContent: log
parsers:
- go
- python
- java
- java-multiline
```

Helm multiline passer template and usage

---

config/crd/bases/kustomization.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1144 
```release-note
```
```docs
```

fix: missing inputs and clusterInputs CRDs in setup.yaml (#1144)

---

apis/fluentbit/v1alpha2/plugins/filter/rewritetag_types.go
apis/fluentbit/v1alpha2/plugins/output/datadog_types.go
apis/fluentbit/v1alpha2/plugins/output/datadog_types_test.go
apis/fluentbit/v1alpha2/plugins/output/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/datadog.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Modified datadog_types.go file to support datadog plugin api key for allowing the value to take from secret.
Fixes #1060 
```release-note
```
```docs
```

fix: support datadog plugin api key to allow for secret injection

---

apis/fluentbit/v1alpha2/filter_types.go
apis/fluentbit/v1alpha2/filter_types_test.go
apis/fluentbit/v1alpha2/plugins/custom/custom_types.go
apis/fluentbit/v1alpha2/plugins/filter/kubernetes_types.go
apis/fluentbit/v1alpha2/plugins/filter/parser_types.go
apis/fluentbit/v1alpha2/plugins/filter/rewritetag_types.go
apis/fluentbit/v1alpha2/plugins/interface.go

Currently there is a recursion bug for namespaced filters. It is caused by the loop within the merge closure, which itself is called for each item. This behaviour let to having the hashed namespace been added multiple times.
Fixes the above explained bug.
```release-note
None
```

Bugfix namespaced filters

---

config/crd/bases/kustomization.yaml
manifests/setup/fluent-operator-clusterRole.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

v2.8.0 includes changes to the _ClusterRole_ and adds a couple new CRDs.  The Helm Chart was updated to include these changes, but the changes were never synced over to the setup manifests.
This means that the `setup.yaml` included with the v2.8.0 is essentially broken.
No issue created.
No.
We somehow need to automate these changes in the future.

Updates setup manifests to be compatible with v2.8.0

---

apis/fluentbit/v1alpha2/plugins/output/forward_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
cmd/doc-gen/main.go
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/forward.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1165
```release-note
Adds the optional `Tag` parameter to fluentbit's output plugin `forward`.
```
```docs
```

add tag parameter to forward output plugin

---

apis/fluentd/v1alpha1/plugins/output/es.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentd/output/es.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Adds cloudId and cloudAuth parameters to fluentd's elasticsearch output plugin. This enables easier configuration of Elastic Cloud authentication.
Fixes #1168
```release-note
Add optional `cloudId` and `cloudAuth` parameters to fluentd's output plugin `elasticsearch`.
```
```docs
```

add cloudId and cloudAuth parameters to elastic

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml

This PR fixes quotes in fluent-operator dpeloyment template.
Fixes #1159
```release-note
None
```

Fix quotes for disable-component-controller argument string in fluent-operator deployment template.

---

cmd/fluent-watcher/fluentd/main.go

There has been an issue with fluentd coming up in docker images. Previous changes were handling only arch, as usr/local/bundle/bin/fluentd. But,
For amd64 it is"/usr/bin/fluentd"
For arm64 it is "/usr/local/bundle/bin/fluentd".
Fixes #1187
```release-note
```
```docs
```

Fix fluentd path issues.

---

charts/fluent-operator/values.yaml
cmd/fluent-watcher/fluentbit/Dockerfile
cmd/fluent-watcher/fluentbit/Dockerfile.debug
config/samples/fluentbit_v1alpha2_fluentbit.yaml
docs/best-practice/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
manifests/kubeedge/fluentbit-fluentbit-edge.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

Updates to 3.0.7 for patches/security updates.
N/A

Update fluentbit to v3.0.7

---

.github/workflows/build-fb-image.yaml
charts/fluent-operator/values.yaml
config/samples/fluentbit_v1alpha2_fluentbit.yaml
docs/best-practice/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
manifests/kubeedge/fluentbit-fluentbit-edge.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

There was a typo in the fluentbit image name.
`ghcr.io/fluent/fluent-operator/fluentbit:3.0.7` should be `ghcr.io/fluent/fluent-operator/fluent-bit:3.0.7` (missing the hyphen).

Fix fluent-bit image name.

---

.github/workflows/build-fd-image.yaml
Makefile
apis/fluentd/v1alpha1/tests/tools.go
charts/fluent-operator/values.yaml
manifests/fluentd/fluentd-cluster-cfg-output-buffer-example.yaml
manifests/fluentd/fluentd-cluster-cfg-output-es.yaml
manifests/fluentd/fluentd-cluster-cfg-output-kafka.yaml
manifests/fluentd/fluentd-mixed-cfgs-multi-tenant-output.yaml
manifests/fluentd/fluentd-mixed-cfgs-output-es.yaml
manifests/fluentd/fluentd-namespaced-cfg-output-es.yaml

https://github.com/fluent/fluent-operator/pull/1198 recently started building a new fluentd:1.17.0 image, but there are several references to the old v1.15.3 images that need to be updated.

Update references to fluentd:1.17.0 image

---

apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/elasticsearch.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR is to support storage.total_limit_size paramater in es output plugin. This properity was introduced since Fluent Bit v1.6 and it is used for limiting the total size in bytes of chunks that can exist in the filesystem for a certain logical output destination.
Fixes # [1194](https://github.com/fluent/fluent-operator/issues/1194)
```release-note
None
```
Refer to **Limiting Filesystem space for Chunks** 
```docs
https://docs.fluentbit.io/manual/administration/buffering-and-storage
```

Add storage total limit size to es plugin

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/templates/fluentbit-containerd-config.yaml
charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/templates/fluentbit-fluentbit-edge.yaml
charts/fluent-operator/templates/fluentbit-lua-config.yaml
charts/fluent-operator/templates/fluentbit-output-loki.yaml
charts/fluent-operator/templates/fluentd-fluentd.yaml

Whenever a helm chart is rendered you can pass it a namespace.
Usually a chart then adds the namespace to the namespaced resources
it is rendering.
This change establishes that behaviour in the fluent-operator chart.
Helm charts tend to respect the namespace that the user passes in to the helm command.
The fluent-operator didn't render a namespace field for the namespaced resources.
```release-note
```
```docs
```

feat(helm): Respect helm release namespace setting

---

charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml

Fixed a bug, which would invalidate the default fluent-bit parsers conf
Fixes #1219
```release-note
None
```
```docs
```

fix parsersfile default parsers.conf path

---

charts/fluent-operator/templates/fluentd-fluentd.yaml
charts/fluent-operator/values.yaml

- Tiny PR to add the same `securityContext` and `podSecurityContext` options to fluentd values which we already have for fluent-bit
Fixes #952 
```release-note
- Add `securityContext` and `podSecurityContext` options to fluentd helm chart values.
```

fix(fluentd): add securityContext and podSecurityContext in values.yaml

---

charts/fluent-operator/templates/fluent-operator-deployment.yaml

This PR is needed to fix the parsing of disableComponentControllers. It seems like the value from helm is being parsed incorrectly. 
I added a small change in code locally and built a custom image to test with chart, while the manager binary itself worked fine without using chart but on parsing the value with chart, I got this logged:
```bash
2024-06-28T15:10:37Z    INFO    setup   Value of disabledControllers    {"value": "\"fluentd\""}
2024-06-28T15:10:37Z    ERROR   setup           {"error": "incorrect value for `-disable-component-controllers` and it will not be proceeded (possible values are: fluent-bit, fluentd)"}
main.main
/workspace/main.go:122
runtime.main
```
Which is the reason why it is reporting it, it reads it as `"\"fluentd\""`. 
It is happening because the `printf ` …

Fixes the parsing of disableComponentControllers in helm

---

apis/fluentd/v1alpha1/plugins/output/opensearch.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
docs/plugins/fluentd/output/opensearch.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This is to allow fluentd opensearch output plugin to use https without verify ssl, just like es output plugin.
Fixes #568
```release-note
None
```
No additional documentation, I have update the existing opensearch output documentation

feat: add 'sslVerify' to opensearch output

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

- Added rbacRules to watch kubernetes events to FluentBit template.
- This way people don't have to modify the CR themselves; it is more user-friendly.
- Added the possibility for custom rbacRules in the operators `values.yaml`. 
- This adds more flexibility to the operator chart
- Fixes issue #923 
- Builds on [this PR](https://github.com/fluent/fluent-operator/pull/1209) 
```release-note
1. Added `rbacRules` option in operators' `values.yaml`
2. No additional action is required from user
```

feat: add rbacRules to values.yaml with events watching as fixed permissions

---

apis/fluentbit/v1alpha2/plugins/output/loki_types.go
apis/fluentbit/v1alpha2/plugins/output/zz_generated.deepcopy.go
apis/fluentd/v1alpha1/plugins/output/loki.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
charts/fluent-operator/templates/fluentbit-output-loki.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/loki.md
docs/plugins/fluentd/output/loki.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

I was searching for an alternative of the openshift-logging-operator. None of the available operators supported bearer token authentication for the Loki output. Since bearer authentication is very useful together wiith Loki and the openshift oauth proxy I decided to make this contribution. 
Fixes #1221 (Not my ticket, by coincidence someone else seems to be missing this feature)
```release-note
* [Fluent-Bit] Additional Parameter "bearerToken" for (Cluster) Output of type Loki
* [Fluent-Bit] Additional Parameter "uri" for (Cluster) Output of type Loki
* [Fluentd] Additional Parameter "bearerTokenFile" for ClusterOutput of type Loki
```
```docs
- [Usage]: https://docs.fluentbit.io/manual/pipeline/outputs/loki
- [Other doc] https://github.com/fluent/fluent-operator/blob/master/docs/plugins/f …
```

Add bearer token auth for loki

---

.github/workflows/build-fb-image.yaml
charts/fluent-operator/values.yaml
manifests/kubeedge/fluentbit-fluentbit-edge.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

Fluentbit 3.1.0 has a known [bug](https://github.com/fluent/fluent-bit/issues/9072) around the `record_modifier` plugin that was fixed in 3.1.2.
I already merged https://github.com/fluent/fluent-operator/pull/1238 and built new images.  This PR just updates the Helm chart and other templates to use 3.1.2 by default.

Bump fluentbit to 3.1.2.

---

.github/workflows/build-fb-image.yaml
.github/workflows/build-fd-image.yaml
cmd/fluent-watcher/README.md

Introduces the ability to release "patch" builds (eg, `fluent-bit:3.1.2-2`) of fluent-bit/fluentd.  This allows us to release changes to our custom builds without overwriting tags that track upstream versions (eg, `fluent-bit:3.1.2`).
Fixes #1241
These workflows were tested successfully in my fork of the repo.
N/A

Support for patch release tags.

---

apis/fluentbit/v1alpha2/plugins/output/open_search_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/open_search.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1257
```release-note
Add compression option to fluentbit opensearch plugin
```
```docs
```

add compression to opensearch output plugin

---

.github/workflows/build-fb-image.yaml
.github/workflows/build-fd-image.yaml
.github/workflows/clone-docker-image-action.yaml

#1246 implemented changes that allow us to release "patch" releases of our fluent-bit and fluentd images,  but it had a few bugs which are addressed in this PR.
Primarily, the logic that promotes and copies images to Dockerhub was broken for various reasons.  This PR centralizes the management of patch tags (eg, `3.1.0-0`) and removes some unnecessary checks/complexity.  This ensures that there is consistent versioning across all tags/patch releases.

Fixes fluentd/fluent-bit image build CI workflows

---

.github/workflows/build-fd-image.yaml
.github/workflows/build-op-image.yaml

#1259 removed the `platform` input from the `clone-docker-image-action` CI workflow but failed to remove it from being passed in the "build fluent operator" workflow which resulted in this error:
```
The workflow is not valid. .github/workflows/build-op-image.yaml (Line: 155, Col: 18): Invalid input, platforms is not defined in the referenced workflow
```
This PR also fixes a Dockerhub promotion issue for the fluentd-arm64-base images.

Fixes "build fluent operator" CI workflow

---

README.md

Mention multiline parser CRDs in README

---

charts/fluent-operator/templates/fluentbit-servicemonitor.yaml

This block in the service monitor fails to correctly use the `with` context:
```
selector:
matchLabels:
{{- include "fluent-operator.selectorLabels" . | nindent 6 }}
{{- with .Values.fluentbit.labels }}
{{- toYaml .Values.fluentbit.labels | nindent 6}}
{{- end }}
```
As a result, populating `.Values.fluentbit.labels` results in:
`Helm install failed for release monitoring/fluent-operator with chart fluent-operator@3.0.0: template: fluent-operator/templates/fluentbit-servicemonitor.yaml:34:24: executing "fluent-operator/templates/fluentbit-servicemonitor.yaml" at <.Values.fluentbit.labels>: nil pointer evaluating interface {}.fluentbit`
None, can create an issue if necessary
```release-note
Fixed the helm template where the service monitor incorrectly refers to variables in a "with" block …
```

Fix service monitor label selector scope

---

cmd/fluent-watcher/fluentbit/main.go

In the commit at https://github.com/fluent/fluent-operator/commit/d8e206004898e6e86f1bcbfeaf192916f9fb6293 I saw that someone accidentally removed the flag.Parse line, which caused fluent-watcher to ignore any CLI flag values, so I added it back
Fixes re
```release-note
```
```docs
```

BUG: re-add accidently removed flag.Parse

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
controllers/fluentbit_controller.go
manifests/setup/fluent-operator-clusterRole.yaml
manifests/setup/setup.yaml

This pull request adds a missing RBAC verb to enable the proper functioning of the Kubernetes events input.
Fixes #1276 
```release-note
None
```

Allow fluent-operator to watch Kubernetes events

---

charts/fluent-operator/templates/fluentbit-servicemonitor.yaml

The fluent-bit service is created with a hardcoded label, https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-fluentBit.yaml#L9
This seems reasonable? So I added this to the ServiceMonitor selector as well, and removed the use of the fluent-operator labels.
Fixes #1292
```release-note
None
```
```docs
```

Set explicit fluent-bit name label selector

---

apis/fluentbit/v1alpha2/plugins/net_types.go
apis/fluentbit/v1alpha2/plugins/output/azure_blob_types.go
apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
apis/fluentbit/v1alpha2/plugins/output/forward_types.go
apis/fluentbit/v1alpha2/plugins/output/gelf_types.go
apis/fluentbit/v1alpha2/plugins/output/http_types.go
apis/fluentbit/v1alpha2/plugins/output/influxdb_types.go
apis/fluentbit/v1alpha2/plugins/output/loki_types.go
apis/fluentbit/v1alpha2/plugins/output/open_search_types.go
apis/fluentbit/v1alpha2/plugins/output/open_telemetry_types.go
apis/fluentbit/v1alpha2/plugins/output/prometheus_remote_write_types.go
apis/fluentbit/v1alpha2/plugins/output/splunk_types.go
apis/fluentbit/v1alpha2/plugins/output/syslog_types.go
apis/fluentbit/v1alpha2/plugins/output/tcp_types.go

It renders attributes from `networking` field and fixes `DNSResolver`.
Fixes #1297
No

bug: Allows to render net properties for outputs

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go

It should allow to use inline code for Lua scripts
Fixes #1287
```release-note
No
```

Render ConfigMap only if key is not empty string

---

.github/workflows/build-fb-image.yaml
CHANGELOG.md
Makefile
README.md
RELEASE.md
charts/fluent-operator/Chart.yaml
charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
charts/fluent-operator/charts/fluentd-crds/Chart.yaml
charts/fluent-operator/values.yaml
cmd/fluent-watcher/fluentbit/Dockerfile
cmd/fluent-watcher/fluentbit/Dockerfile.debug
manifests/kubeedge/fluentbit-fluentbit-edge.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

Fixes #
```release-note
update fluentbit to 3.1.5
```
```docs
```

update fluentbit to 3.1.5

---

Makefile

The kubernetes annotation is too long for fluentd CRD and we can't use `kubectl apply` any more. 
see also:
- https://github.com/prometheus-operator/prometheus-operator/pull/4349
- https://github.com/kubernetes/kubectl/issues/712
Fixes #1268
```release-note
None
```
```docs
```

fix annotations too long issue

---

apis/fluentbit/v1alpha2/plugins/output/open_telemetry_types.go
apis/fluentbit/v1alpha2/plugins/output/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/open_telemetry.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

It adds the `logs_body_key_attributes` option for the OpenTelemetry output plugin.
Fixes #1321
```release-note
Add logsBodyKeyAttributes boolean option to opentelemetry output plugin.
```
```docs
```

Add logs_body_key_attributes option for OpenTelemetry output plugin

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

This PR allows us to configure the initContainers in fluentbit custom resource. Fluentbit CRD schema already has the option to configure initContainers. So just exposing the same in values.yaml.
Fixes #1319 
```release-note
None
```
```docs
```

Expose fluentbit init-container values in helm chart

---

apis/fluentbit/v1alpha2/plugins/output/syslog_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/syslog.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR is to support the storage.total_limit_size parameter in the syslog output plugin. This property was introduced in Fluent Bit v1.6 and it is used for limiting the total size in bytes of chunks that can exist in the filesystem for a certain logical output destination.
Fixes #1317 
```release-note
Added the ability to specify the storage.total_limit_size parameter for the syslog output plugin.
```
```docs
- [Usage]: https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentbit/output/syslog.md
```

Support storage.total_limit_size in syslog plugin

---

apis/fluentbit/v1alpha2/plugins/output/elasticsearch_types.go
apis/fluentbit/v1alpha2/plugins/output/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/elasticsearch.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1324
```release-note
```
```docs
```

feat: add cloudAuthSecret & awsAuthSecret

---

charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
charts/fluent-operator/templates/fluent-operator-clusterRoleBinding.yaml
charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/templates/fluentbit-lua-config.yaml
charts/fluent-operator/templates/serviceaccount.yaml
charts/fluent-operator/values.yaml

Fixes https://github.com/fluent/fluent-operator/issues/1308
Fixes #
```release-note
Add option to disable operator resources in Helm chart
```
```docs
Now can deploy fluent-operator and fluentbit one after another like this
helm install fluent-operator --create-namespace -n fluent charts/fluent-operator/  --set containerRuntime=containerd --set operator.enable=true --set fluentbit.enable=false
helm install fluentbit --create-namespace -n fluent charts/fluent-operator/  --set containerRuntime=containerd --set operator.enable=false --set fluentbit.enable=true
If operator.enable be set to false, this will disable the creation of ClusterRole, ClusterRoleBinding,Deployment, and ServiceAccount resources
```

Add option to disable operator resources in Helm chart

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

Signed-off-by: Zoltán Reegn <zoltan.reegn@gmail.com>
Fixes #
```release-note
```
```docs
```

feat(helm): expose args and command attributes for FluentBit CRD

---

CHANGELOG.md
README.md
RELEASE.md
charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
charts/fluent-operator/charts/fluentd-crds/Chart.yaml

release 3.2.0
Fixes #
```release-note
```
```docs
```

release 3.2.0

---

charts/fluent-operator/values.yaml
manifests/fluentd/fluentd-cluster-cfg-output-buffer-example.yaml
manifests/fluentd/fluentd-cluster-cfg-output-es.yaml
manifests/fluentd/fluentd-cluster-cfg-output-kafka.yaml
manifests/fluentd/fluentd-mixed-cfgs-multi-tenant-output.yaml
manifests/fluentd/fluentd-mixed-cfgs-output-es.yaml
manifests/fluentd/fluentd-namespaced-cfg-output-es.yaml
manifests/quick-start/fluentd-forward.yaml
manifests/quick-start/fluentd-http.yaml

Reference the latest build.
Fix fluentd image references so they all point to ghcr.io
Signed-off-by: Zoltán Reegn <zoltan.reegn@gmail.com>
Fixes #
```release-note
```
```docs
```

Update fluentd image references

---

.github/workflows/build-fb-image.yaml
Makefile
README.md
charts/fluent-operator/values.yaml
cmd/fluent-watcher/fluentbit/Dockerfile
cmd/fluent-watcher/fluentbit/Dockerfile.debug
config/samples/fluentbit_v1alpha2_fluentbit.yaml
docs/best-practice/forwarding-logs-via-http/deploy/fluentbit-fluentBit.yaml
manifests/kubeedge/fluentbit-fluentbit-edge.yaml
manifests/logging-stack/fluentbit-fluentBit.yaml
manifests/quick-start/fluentbit.yaml
manifests/regex-parser/fluentbit-fluentBit.yaml

Fixes #
```release-note
```
```docs
```

Update fluent-bit to 3.1.8

---

apis/fluentbit/v1alpha2/plugins/output/influxdb_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This PR removes the validation of the ipv4, ipv6 and hostname. This is because the Kubebuilder doesn't support using multiple format validations for a single field. In original code, there were three formation validations(hostname, ipv4, ipv6), but only the last one(ipv6) would be applied.
This PR also remedies port range. The highest valid port number is 65535, not 65536. Port 0 is a reserved port in TCP/IP
Fixes #1359
```release-note
```
```docs
```

Remove influxdb host validation in  ClusterOutput

---

.github/workflows/release-tool.yaml

Automate the release process, it will create a release pr (step 2, example #1354 ) automatically. 
We need another automation for step1, example #1343 
Fixes #
```release-note
```
```docs
```

add release-tool workflow to generate release pr

---

controllers/fluent_controller_finalizer.go
controllers/fluentbit_controller.go
docs/plugins/fluentbit/output/azure_log_analytics.md

To support `kubectl rollout restart ds/sts`, this pr preserves the `kubectl.kubernetes.io/restartedAt` annotation when reconciling. 
Fixes #
```release-note
```
```docs
```

feat: support rollout restart for daemonset and statefulset

---

charts/fluent-operator/README.md

Adds a README to the Helm chart which will get synced to https://github.com/fluent/helm-charts/tree/main/charts/fluent-operator

Adds README to Helm chart

---

charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml
charts/fluent-operator/values.yaml

Deploy fluent-bit configmap and secret in the namespace provided in the namespaceClusterFbCfg which is used in ClusterFluentBitConfig customresource > spec section. If it is not defined, they are created in the namespace of the fluent-operator.
Signed-off-by: Bharathi Talakola <divya.cs237@gmail.com>
At present "fluent-bit-config" secret is getting created in the fluent-operator namespace by default. It can be configured using "namespace" key from ClusterFluentBitConfig CRD but this namespace key is not configured at the CR level.
https://github.com/fluent/fluent-operator/blob/release-3.2/charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfluentbitconfigs.yaml#L191-L231.
Hence added namespace field to ClusterFluentBitConfig customresource > spec section.
Fixes: …

Adding namespaceClusterFbCfg to ClusterFluentBitConfig custom resource.

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/templates/fluent-operator-deployment.yaml
charts/fluent-operator/values.yaml

The helm chart currently does not allow adding affinity rules to the pods created by the fluent-operator deployment. This PR adds the ability to configure both affinity and anti-affinity rules for the fluent-operator pods scheduling on nodes.
Fixes #1291
```release-note
```
```docs
```

 Add affinity support for fluent-operator deployment

---

cmd/fluent-watcher/fluentd/Dockerfile.amd64
cmd/fluent-watcher/fluentd/Dockerfile.arm64
cmd/fluent-watcher/fluentd/Dockerfile.arm64.base

Hi, I want to use [Kafka FluentD plugin](https://github.com/fluent/fluent-plugin-kafka), but the base library [ruby-kafka is deprecated](https://github.com/zendesk/ruby-kafka?tab=readme-ov-file#deprecation-notice), which is also not compatible with my Strimzi Kafka installation. Then I tried to use the new rdkafka part of this plugin, but it fails with the fluent-operator image because it needs to have the C rdkafka library installed as well. I tried to create my own image, but now I want to publish this fix for all users.
None
```release-note
- rdkafka part of fluent-plugin-kafka can be now used with fluent-operator FluentD image.
```
```docs
```

feat: add rdkafka gem installation to Dockerfiles for fluent-watcher

---

.github/workflows/lint-test.yaml
apis/fluentbit/v1alpha2/plugins/input/tail_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterinputs.yaml
config/crd/bases/fluentbit.fluent.io_clusterinputs.yaml
docs/plugins/fluentbit/input/tail.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1422
```release-note
```
```docs
```

feat: support fluentbit tail offsetKey parameters

---

apis/fluentbit/v1alpha2/plugins/input/tail_types.go
apis/fluentbit/v1alpha2/plugins/output/kafka_types.go
apis/fluentbit/v1alpha2/plugins/output/loki_types.go
apis/fluentbit/v1alpha2/plugins/output/open_search_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterinputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
charts/fluent-operator/templates/fluentbit-output-loki.yaml
charts/fluent-operator/values.yaml
config/crd/bases/fluentbit.fluent.io_clusterinputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

retry_limit param for default loki output
Threaded API param for tail input
Workers API param for kafka/loki outputs
TotalLimitSize  API param for kafka/loki outputs

Additional params for input & output APIs + ability to set retry_limit for default loki output

---

.github/workflows/bump-fluent-bit-version.yaml
Makefile

Add a pipeline to bump fluent-bit version
Fixes #
```release-note
```
```docs
```

feat: add pipeline to bump fluent bit version

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

There is FluentBit object built-in helm chart. Since FluentBit supports livenessProbes in CRD, it will be good to have ability to define health probe for built-in FluentBit object.
We got case with fluent-bit processes hang, metrics/api endpoints are not respond in this case, livenessProbe will help a lot.

feat: Add livenessProbe to FluentBit template (fluentbit-fluentBit.yaml)

---

apis/fluentd/v1alpha1/plugins/output/es.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentd/output/es.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

CRDs in current form and operator itself lack support for `reload_after` and `sniffer_class_name` elasticsearch output parameters.
Fixes #
```
No.
```
```
https://github.com/uken/fluent-plugin-elasticsearch?tab=readme-ov-file#sniffer-class-name
https://github.com/uken/fluent-plugin-elasticsearch?tab=readme-ov-file#reload-after
```

feat: Add support for reload_after, sniffer_class_name es output parameters

---

Makefile
apis/fluentd/v1alpha1/tests/tools.go
charts/fluent-operator/values.yaml
manifests/fluentd/fluentd-cluster-cfg-output-buffer-example.yaml
manifests/fluentd/fluentd-cluster-cfg-output-es.yaml
manifests/fluentd/fluentd-cluster-cfg-output-kafka.yaml
manifests/fluentd/fluentd-mixed-cfgs-multi-tenant-output.yaml
manifests/fluentd/fluentd-mixed-cfgs-output-es.yaml
manifests/fluentd/fluentd-namespaced-cfg-output-es.yaml
manifests/quick-start/fluentd-forward.yaml
manifests/quick-start/fluentd-http.yaml

Update fluentd to v1.17.1.

---

.github/workflows/release-tool.yaml

Just noticed that the target release branch name is release-x.y (release-3.3), instead of release-vx.y.z, updated the naming in the pipeline to be aligned with the current naming convention.
Fixes #
```release-note
```
```docs
```

fix: fix pipeline bugs and improve the validation

---

.github/workflows/build-fb-image.yaml
.github/workflows/build-fluentd-image.yaml
.github/workflows/build-op-image.yaml
.github/workflows/bump-fluent-bit-version.yaml
.github/workflows/lint-test.yaml
.github/workflows/main.yaml
.github/workflows/release-tool.yaml
.github/workflows/scan-docker-image-action.yaml

For compliance with best practices and prevent supply chain attacks this PR pins all GitHub actions on their commit hash. 
Dependabot understands this format and will raise PRs for new releases (once a month with current dependabot configuration).
I made separate commits for each action that I pinned for traceability in the repo (would be great to merge this using a merge commit to keep that traceability).
For the reviewer you can navigate to each action and compare the hash related to a specific version as following example.

Pin GitHub actions on commit hash according to best practices

---

.github/workflows/build-fb-image.yaml
.github/workflows/main.yaml

This builds on top of #1513 should be `(rebase merged)` after #1513 is merged. This to keep a clear and concise Git history.
Using this PR the Go version is controlled completely using the go.mod file in the root of the repository. This makes it easier to ensure all workflows use the same go version and makes it easier to bump Go to a newer version in the entire project by defining this just in a single location.

Use go.mod version in workflows

---

charts/fluent-operator/templates/fluentbit-output-loki.yaml

Adds a newline before the `fluentbit.output.loki.labelKeys` to prevent it from being appended to the previous block.
Fixes #1508
None
```release-note
```
```docs
```

Move dash so that labelKeys and removeKeys on separate line

---

controllers/fluentbitconfig_controller.go
controllers/fluentdconfig_controller.go
docs/best-practice/forwarding-logs-via-http/main.go
tests/e2e/fluentd/cfgrender_suite_test.go

Fixes the findings as shown here
https://github.com/fluent/fluent-operator/actions/runs/13957612017/job/39072438631?pr=1516

go-vet: Fix the Go vet findings

---

.github/workflows/build-fb-image.yaml
.github/workflows/main.yaml

The caching is builtin to the setup-go action since 5.0.0

actions: Remove cache action for Go

---

.github/workflows/build-fluentbit-image.yaml

The "publish fluentbit image" CI pipeline is currently failing with:
This is because the `manifest` job does not have permission to publish GH packages.

(ci/fluentbit) fix: Adds permission to publish packages 

---

apis/fluentbit/v1alpha2/plugins/input/kubernetes_events_types.go

Fixes a bug with the config generation of the Kubernetes Events input.
`DB_Sync` is not a valid configuration option, it should be `DB.Sync`.
Generated config:
```
[Input]
Name    kubernetes_events
Alias    system-events
Tag    kube-events
DB    /fluent-bit/tail/system-events-pos.db
DB_Sync    normal
Kube_URL    https://kubernetes.default.svc:443
Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
```
Error:
```
[2025/04/04 01:53:01] [error] [config] kubernetes_events: unknown configuration property 'db_sync'. The following properties are allowed: kube_url, interval_sec, interval_nsec, tls.debug, tls.verify, tls.vhost, kube_ca_file, kube_ca_path, kube_token_file, kube_token_ttl, kube_request_limit, …
```

Fix Kubernetes Events DBSync config

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

When `kind: FluentBit` is created using the official HELM chart, `positionDB` is locked to `hostPath.path: /var/lib/fluent-bit/`:
https://github.com/fluent/fluent-operator/blob/07df44ddb20e305570cedc6e87d500ca6bee87e3/charts/fluent-operator/templates/fluentbit-fluentBit.yaml#L24-L26
I prefer flexibility: the user can replace this value.
Fixes #1547
```release-note
None
```
```docs
```

feat(charts): Add ability for custom `positionDB` for `FluentBit`

---

charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
charts/fluent-operator/templates/fluent-operator-clusterRoleBinding.yaml
charts/fluent-operator/values.yaml

Enable or disable ClusterRole and RoleBinding creation.
The use case is to allow users to use this chart in clusters where creating such objetcs is not allowed by helm deployment.
Also, it's adding the ability to customize the rules, as not all of them are required for the operator to work.
Fixes (https://github.com/fluent/helm-charts/issues/215)
None
To use this feature, simply update a propertie  in the values.
```docs
...
operator:
rbac:
create: true
...
```
* set `true` for enable but it's default value.
* set `false` for disable.

feat(helm/fluent-operator): add option to disable rbac creation

---

pkg/operator/sts.go

When `spec.globalInputs/*/forward` is non-nil, but the port is unset, the operator panics and crashes. This PR adds a nil check to prevent this.
N/A
```release-note
Fixed the operator panicking when Fluentd global inputs are set but no port is provided
```
N/A

Fixed nil pointer dereference (panic) when port numbers are unset

---

apis/fluentbit/v1alpha2/plugins/input/tail_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterinputs.yaml
config/crd/bases/fluentbit.fluent.io_clusterinputs.yaml
docs/plugins/fluentbit/input/tail.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

[This config value](https://docs.fluentbit.io/manual/pipeline/inputs/tail#config) is missing from the fluentbit input CRD.
N/A
```release-note
Added the ability to set `DB.locking` on fluentbit tail inputs
```
N/A

Added the ability to set `DB.locking` on fluentbit tail inputs

---

apis/fluentbit/v1alpha2/plugins/filter/kubernetes_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfilters.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_filters.yaml
config/crd/bases/fluentbit.fluent.io_clusterfilters.yaml
config/crd/bases/fluentbit.fluent.io_filters.yaml
docs/plugins/fluentbit/filter/kubernetes.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

[This config value](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#configuration-parameters) is missing from the fluentbit filter CRD.
N/A
```release-note
Added the ability to set `Owner_References` on fluentbit kubernetes filter
```
N/A

Added the ability to set `Owner_References` on fluentbit kubernetes filter

---

charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml
charts/fluent-operator/values.yaml

In our use case we would like to customize the bufferChunkSize dependent on the client need and we see that the property is not exposed yet in the helmchart even though it is already in the crd.

Support setting fluent-bit bufferChunkSize for tail input

---

charts/fluent-operator/templates/fluentbit-clusterinput-systemd.yaml
charts/fluent-operator/templates/fluentbit-output-forward.yaml
charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml

By adding quotes you prevent users from injecting yaml based template attacks.

helm-chart: Prevent few more occasions of template injection

---

apis/fluentd/v1alpha1/plugins/output/http.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentd/output/http.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

The fluentd HTTP output plugin is currently missing support for [the `compress` field](https://docs.fluentd.org/output/http#compress).
N/A
```release-note
Added support for HTTP request compression to the Fluentd HTTP output plugin configuration.
```
N/A

Add support for compression to the Fluentd HTTP output plugin

---

charts/fluent-operator/templates/fluentbit-clusterfilter-multiline.yaml
charts/fluent-operator/values.yaml

- adds missing values to the multiline ClusterFilter object
Fixes https://github.com/fluent/fluent-operator/issues/1580
```release-note
None
```
```docs
```

Add missing multiline ClusterFilter values

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
apis/fluentbit/v1alpha2/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbitconfigs.yaml
config/crd/bases/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
config/crd/bases/fluentbit.fluent.io_fluentbitconfigs.yaml
docs/fluentbit.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

implements #1586 closes #1586
This enables the users to turn debug traces on/off, as per https://docs.fluentbit.io/manual/administration/troubleshooting
I validate that I can spin up the operator and:
- enable/disable the option, it respects the SIGHUP&hot reload correcty
- see the expected result - I can now switch to a debug image and use the  curl API to enable tracing
In my testing I used the following spec:
```
kind: FluentBit
metadata:
name: fluent-bit
namespace: fluent
labels:
app.kubernetes.io/name: fluent-bit
spec:
image: ghcr.io/fluent/fluent-operator/fluent-bit:4.0-debug
fluentBitConfigName: fluent-bit-config
---
kind: ClusterFluentBitConfig
metadata:
name: fluent-bit-config
namespace: fluent …
```

expose Enable_Chunk_Trace in the crd, enabling TAP debuging

---

.github/workflows/helm-ci.yaml
.github/workflows/main.yaml

This ensures PRs, like this will run the helm ci
https://github.com/fluent/fluent-operator/pull/1585
Moved it out of the main workflow so it doesn't affect running other workflows that shouldn't be required so we can have bit more finegraining on the paths.

ci: Ensure helm tests run on changes to the chart

---

pkg/operator/fluent-bit-service.go

When `spec.labels` is defined, it is used to label created daemonset pods instead of `metadata.labels`. This causes the service, which always uses `metadata.labels`, to not select pods in some cases.
Unfortunately, because `spec.labels` is defined as `map[string]string` instead of a `*map[string]string`, it's not possible to tell the difference between a null `spec.labels` value (`labels: ~`, `labels: null`, or `labels` not set) and an empty `spec.labels` value (`labels: {}`). I think it's highly unlikely that anybody is doing this today, but if so, this could possibly be a breaking change.
N/A
```release-note
Fixed fluent bit service not always selecting pods when pod labels are set via `spec.labels`.
```
N/A

Fix fluentbit service selector not using pod labels when defined

---

apis/fluentbit/v1alpha2/plugins/output/open_search_types.go
docs/plugins/fluentbit/output/open_search.md

This PR fixes `fluentbit/plugins/open_search.md` that still referenced Elasticsearch
No issue has been created for this

Fix(doc): open_search.md referencing elasticsearch name

---

apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_fluentbitconfigs.yaml
config/crd/bases/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
config/crd/bases/fluentbit.fluent.io_fluentbitconfigs.yaml
docs/best-practice/monitoring.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Although `fluent-bit` supports IPv6, HTTP listening on an IPv6 address fails due to the address validation currently supporting IPv4 only. Improve the RegEx to support both IPv4 and IPv6 good enough™
Notes:
- the IPv6 RegEx part matches also the unspecified address `::`
- the IPv4 RegEx part was improved to match the dot delimiter `.` literally (it previously matched every character, due to missing escaping)
Fixes https://github.com/fluent/fluent-operator/issues/1615

Support both IPv4 and IPv6 addresses in http_listen configuration

---

charts/fluent-operator/Chart.yaml
charts/fluent-operator/charts/fluent-bit-crds/Chart.yaml
charts/fluent-operator/charts/fluentd-crds/Chart.yaml

helm-chart: patch 3.4 release

---

charts/fluent-operator/templates/fluentbit-fluentBit.yaml
charts/fluent-operator/values.yaml

We still encounter hangs during logs reopen (on rotation), fluent reloads. Seems that it's related to issue: https://github.com/fluent/fluent-bit/issues/5485
What we can do quick - is to analyze metrics of fluent (fluentbit_input_records_total) in livenessProbes and trigger pod restart if no logs on input during some time specified. 
I want to be able to use not only http probe, but any definition possible for livenessProbe. 
PR does not have breaking changes, yaml will be generated the same as in previous version.

Make fluentbit livenessProbe more flexible

---

apis/fluentbit/v1alpha2/plugins/output/kinesis_types.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

Fixes #1613
```release-note
Validate the region filed and its value in Kinesis output plugin. the region is required and is not allowed empty. 
```
```docs
```

Validate region and its value in Kinesis Output plugin

---

apis/fluentbit/v1alpha2/plugins/output/s3_types.go
apis/fluentbit/v1alpha2/plugins/output/s3_types_test.go
apis/fluentbit/v1alpha2/plugins/output/zz_generated.deepcopy.go
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluent-bit-crds/crds/fluentbit.fluent.io_outputs.yaml
config/crd/bases/fluentbit.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentbit.fluent.io_outputs.yaml
docs/plugins/fluentbit/output/s3.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

The Operator does not pass the "workers" parameter to the S3 Output plugin. This PR is so that that parameter will be recognized and passed.
Fixes #1646
```release-note
Support `Workers` parameter for S3 Output Plugin
```
```docs
```

Add `workers` param for s3 output

---

charts/fluent-operator/values.yaml

Fixes linting errors detected here https://github.com/fluent/helm-charts/pull/622.
The CI workflow that runs `ct` is not currently operational.  We need to fix this.

Fix helm chart linting errors

---

apis/fluentd/v1alpha1/plugins/output/s3.go
apis/fluentd/v1alpha1/plugins/output/types.go
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_clusteroutputs.yaml
charts/fluent-operator/charts/fluentd-crds/crds/fluentd.fluent.io_outputs.yaml
config/crd/bases/fluentd.fluent.io_clusteroutputs.yaml
config/crd/bases/fluentd.fluent.io_outputs.yaml
docs/plugins/fluentd/output/s3.md
manifests/setup/fluent-operator-crd.yaml
manifests/setup/setup.yaml

This allows `AwsKeyId` and `AwsSecKey` to be pulled from secrets like the cloudwatch output plugin
Fixes #
```release-note
```
```docs
```

allow s3 output plugin to get keys from secrets
